import type {
  BattleRules,
  Collection,
  DexMilestone,
  EvolutionMethod,
  EvolutionOverride,
  GameContentData,
  ProgressReward,
  LootEntry,
  ShopCategory,
  ShopEntry,
  Trainer,
  TrainerPokemon,
  Zone,
} from './schemas';

/**
 * Contenu de test, importé en base au premier lancement (version 1, publiée).
 * Tout reste modifiable ensuite dans le panneau d'admin. Valeurs : PLAN.md, section 7.
 */

const ALL_DURATIONS = [15, 60, 240, 480];

const enc = (speciesId: number, weight: number, minLevel: number, maxLevel: number) => ({
  speciesId,
  weight,
  minLevel,
  maxLevel,
});
const loot = (itemId: string, chance: number, min = 1, max = min): LootEntry => ({
  itemId,
  chance,
  min,
  max,
});

const zones: Zone[] = [
  {
    id: 'route-1',
    regionId: 'kanto',
    order: 0,
    name: 'Route 1',
    description: 'Les hautes herbes entre Bourg Palette et Jadielle. Idéal pour débuter.',
    image: null,
    habitat: 'grassland',
    minPower: 0,
    requiredTypes: [],
    affinityTypes: ['normal', 'flying'],
    durationsMinutes: ALL_DURATIONS,
    encounters: [
      enc(19, 30, 2, 4),
      enc(16, 30, 2, 4),
      enc(21, 15, 3, 5),
      enc(29, 10, 3, 5),
      enc(32, 10, 3, 5),
      enc(43, 5, 4, 6),
    ],
    lootTableId: 'butin-route',
    unlock: { type: 'always' },
  },
  {
    id: 'foret-de-jade',
    regionId: 'kanto',
    order: 1,
    name: 'Forêt de Jade',
    description: 'Une forêt dense où grouillent les insectes. On y aperçoit parfois un Pikachu.',
    image: null,
    habitat: 'forest',
    minPower: 100,
    requiredTypes: [],
    affinityTypes: ['bug', 'grass'],
    durationsMinutes: ALL_DURATIONS,
    encounters: [
      enc(10, 30, 3, 6),
      enc(13, 30, 3, 6),
      enc(11, 10, 5, 7),
      enc(14, 10, 5, 7),
      enc(69, 12, 5, 8),
      enc(25, 3, 5, 8),
    ],
    lootTableId: 'butin-foret',
    unlock: { type: 'regionDexPercent', regionId: 'kanto', percent: 3 },
  },
  {
    id: 'mont-selenite',
    regionId: 'kanto',
    order: 2,
    name: 'Mont Sélénite',
    description: 'Une grotte sombre, réputée pour ses météorites… et ses Mélofée.',
    image: null,
    habitat: 'cave',
    minPower: 180,
    requiredTypes: [],
    affinityTypes: ['rock', 'ground'],
    durationsMinutes: ALL_DURATIONS,
    encounters: [
      enc(41, 40, 6, 10),
      enc(74, 30, 7, 10),
      enc(46, 15, 8, 11),
      enc(27, 10, 8, 11),
      enc(35, 5, 8, 12),
    ],
    lootTableId: 'butin-grotte',
    unlock: { type: 'regionDexPercent', regionId: 'kanto', percent: 6 },
  },
  {
    id: 'cap-azuria',
    regionId: 'kanto',
    order: 3,
    name: 'Cap Azuria',
    description: 'Les berges au nord d’Azuria. Il faut au moins un Pokémon Eau pour s’y aventurer.',
    image: null,
    habitat: 'waters-edge',
    minPower: 250,
    requiredTypes: [{ type: 'water', count: 1 }],
    affinityTypes: ['water'],
    durationsMinutes: [60, 240, 480],
    encounters: [
      enc(129, 35, 8, 15),
      enc(118, 20, 10, 15),
      enc(60, 20, 10, 15),
      enc(54, 12, 12, 16),
      enc(72, 10, 12, 16),
      enc(120, 3, 14, 18),
    ],
    lootTableId: 'butin-mer',
    unlock: { type: 'regionDexPercent', regionId: 'kanto', percent: 10 },
  },
];

const mon = (speciesId: number, level: number): TrainerPokemon => ({
  speciesId,
  level,
  iv: null,
  nature: null,
});
const noRules = (): BattleRules => ({
  teamSize: null,
  maxLevel: null,
  requiredTypes: [],
  forbiddenTypes: [],
  minPower: 0,
});
const TRAINER_SPRITES = 'https://play.pokemonshowdown.com/sprites/trainers';

const trainers: Trainer[] = [
  {
    id: 'gamin-tom',
    regionId: 'kanto',
    zoneId: 'route-1',
    order: 0,
    name: 'Tom',
    trainerClass: 'Gamin',
    sprite: `${TRAINER_SPRITES}/youngster.png`,
    team: [mon(19, 4)],
    durationMinutes: 10,
    rules: noRules(),
    money: 80,
    lootTableId: 'butin-route',
    lootRolls: 1,
    badge: null,
    repeatable: true,
    cooldownMinutes: null,
    koMinutes: null,
    unlock: { type: 'always' },
  },
  {
    id: 'fillette-lise',
    regionId: 'kanto',
    zoneId: 'route-1',
    order: 1,
    name: 'Lise',
    trainerClass: 'Fillette',
    sprite: `${TRAINER_SPRITES}/lass.png`,
    team: [mon(16, 4), mon(29, 5)],
    durationMinutes: 15,
    rules: noRules(),
    money: 120,
    lootTableId: 'butin-route',
    lootRolls: 1,
    badge: null,
    repeatable: true,
    cooldownMinutes: null,
    koMinutes: null,
    unlock: { type: 'trainerDefeated', trainerId: 'gamin-tom' },
  },
  {
    id: 'scout-rick',
    regionId: 'kanto',
    zoneId: 'foret-de-jade',
    order: 2,
    name: 'Rick',
    trainerClass: 'Scout',
    sprite: `${TRAINER_SPRITES}/bugcatcher.png`,
    team: [mon(10, 6), mon(13, 6), mon(14, 7)],
    durationMinutes: 20,
    rules: noRules(),
    money: 180,
    lootTableId: 'butin-foret',
    lootRolls: 2,
    badge: null,
    repeatable: true,
    cooldownMinutes: null,
    koMinutes: null,
    unlock: { type: 'regionDexPercent', regionId: 'kanto', percent: 3 },
  },
  {
    id: 'pierre',
    regionId: 'kanto',
    zoneId: null,
    order: 3,
    name: 'Pierre',
    trainerClass: 'Champion d’arène',
    sprite: `${TRAINER_SPRITES}/brock.png`,
    team: [mon(74, 12), mon(95, 14)],
    durationMinutes: 60,
    rules: noRules(),
    money: 1200,
    lootTableId: 'butin-grotte',
    lootRolls: 3,
    badge: { name: 'Badge Roche', image: null },
    repeatable: false,
    cooldownMinutes: null,
    koMinutes: null,
    unlock: { type: 'trainerDefeated', trainerId: 'scout-rick' },
  },
  {
    id: 'campeur-leo',
    regionId: 'kanto',
    zoneId: 'mont-selenite',
    order: 4,
    name: 'Léo',
    trainerClass: 'Campeur',
    sprite: `${TRAINER_SPRITES}/camper.png`,
    team: [mon(27, 10), mon(23, 11)],
    durationMinutes: 30,
    rules: { ...noRules(), maxLevel: 15 },
    money: 300,
    lootTableId: 'butin-grotte',
    lootRolls: 2,
    badge: null,
    repeatable: true,
    cooldownMinutes: null,
    koMinutes: null,
    unlock: { type: 'badgeCount', count: 1 },
  },
  {
    id: 'ondine',
    regionId: 'kanto',
    zoneId: null,
    order: 5,
    name: 'Ondine',
    trainerClass: 'Championne d’arène',
    sprite: `${TRAINER_SPRITES}/misty.png`,
    team: [mon(120, 18), mon(121, 21)],
    durationMinutes: 60,
    rules: { ...noRules(), minPower: 250 },
    money: 2100,
    lootTableId: 'butin-mer',
    lootRolls: 3,
    badge: { name: 'Badge Cascade', image: null },
    repeatable: false,
    cooldownMinutes: null,
    koMinutes: 120,
    unlock: { type: 'badgeCount', count: 1 },
  },
];

const shopCategories: ShopCategory[] = [
  { id: 'balls', name: 'Balls', icon: null, order: 0 },
  { id: 'baies', name: 'Baies', icon: null, order: 1 },
  { id: 'elevage', name: 'Élevage', icon: null, order: 2 },
  { id: 'evolution', name: 'Évolution', icon: null, order: 3 },
];

const article = (
  id: string,
  itemId: string,
  categoryId: string,
  order: number,
  price: number,
  extra: Partial<ShopEntry> = {},
): ShopEntry => ({
  id,
  itemId,
  categoryId,
  order,
  price,
  lotSize: 1,
  unlock: { type: 'always' },
  lockedVisibility: 'locked',
  purchaseLimit: null,
  availableFrom: null,
  availableUntil: null,
  enabled: true,
  ...extra,
});

/** Prix : PLAN.md, section 7. Super / Hyper Balls débloquées par les badges Roche et Cascade. */
const shopEntries: ShopEntry[] = [
  article('poke-ball', 'poke-ball', 'balls', 0, 200),
  article('poke-ball-x10', 'poke-ball', 'balls', 1, 1800, { lotSize: 10 }),
  article('great-ball', 'great-ball', 'balls', 2, 600, {
    unlock: { type: 'trainerDefeated', trainerId: 'pierre' },
  }),
  article('ultra-ball', 'ultra-ball', 'balls', 3, 1200, {
    unlock: { type: 'trainerDefeated', trainerId: 'ondine' },
  }),
  article('razz-berry', 'razz-berry', 'baies', 0, 150),
  article('razz-berry-x5', 'razz-berry', 'baies', 1, 600, { lotSize: 5 }),
  article('everstone', 'everstone', 'elevage', 0, 10_000, {
    unlock: { type: 'badgeCount', count: 1 },
  }),
  article('destiny-knot', 'destiny-knot', 'elevage', 1, 10_000, {
    unlock: { type: 'eggsHatched', count: 10 },
    lockedVisibility: 'hidden',
    purchaseLimit: { lots: 1, period: 'week' },
  }),
  article('moon-stone', 'moon-stone', 'evolution', 0, 3000, {
    unlock: { type: 'regionDexPercent', regionId: 'kanto', percent: 25 },
  }),
  article('water-stone', 'water-stone', 'evolution', 1, 3000, {
    unlock: { type: 'regionDexPercent', regionId: 'kanto', percent: 25 },
  }),
  article('thunder-stone', 'thunder-stone', 'evolution', 2, 3000, {
    unlock: { type: 'regionDexPercent', regionId: 'kanto', percent: 25 },
  }),
  article('fire-stone', 'fire-stone', 'evolution', 3, 3000, {
    unlock: { type: 'regionDexPercent', regionId: 'kanto', percent: 25 },
  }),
  article('leaf-stone', 'leaf-stone', 'evolution', 4, 3000, {
    unlock: { type: 'regionDexPercent', regionId: 'kanto', percent: 25 },
  }),
  article('linking-cord', 'linking-cord', 'evolution', 5, 5000, {
    unlock: { type: 'badgeCount', count: 2 },
  }),
];

const method = (m: Partial<EvolutionMethod>): EvolutionMethod => ({
  minLevel: null,
  itemId: null,
  minHappiness: null,
  timeOfDay: null,
  ...m,
});
const evolution = (from: number, to: number, ...methods: EvolutionMethod[]): EvolutionOverride => ({
  id: `${from}-${to}`,
  fromSpeciesId: from,
  toSpeciesId: to,
  enabled: true,
  methods,
});

/**
 * PokéAPI mélange les conditions des formes régionales (Miaouss d'Alola évolue par le bonheur,
 * Goupix d'Alola par la Pierre Glace…) : on garde ici la méthode de la forme de Kanto.
 */
const evolutionOverrides: EvolutionOverride[] = [
  evolution(52, 53, method({ minLevel: 28 })),
  evolution(27, 28, method({ minLevel: 22 })),
  evolution(37, 38, method({ itemId: 'fire-stone' })),
  evolution(100, 101, method({ minLevel: 30 })),
  evolution(79, 80, method({ minLevel: 37 })),
];

const reward = (r: Partial<ProgressReward>): ProgressReward => ({
  currency: 0,
  items: [],
  expeditionSlots: 0,
  battleSlots: 0,
  daycareSlots: 0,
  bonuses: [],
  ...r,
});

/** Paliers du Pokédex de Kanto : emplacements, Balls, argent (PLAN.md, section 2.8). */
const dexMilestones: DexMilestone[] = [
  {
    id: 'kanto-10',
    order: 0,
    name: 'Apprenti de Kanto',
    regionId: 'kanto',
    shiny: false,
    percent: 10,
    rewards: reward({ expeditionSlots: 1, items: [{ itemId: 'great-ball', quantity: 5 }] }),
  },
  {
    id: 'kanto-25',
    order: 1,
    name: 'Explorateur de Kanto',
    regionId: 'kanto',
    shiny: false,
    percent: 25,
    rewards: reward({ battleSlots: 1, daycareSlots: 1, currency: 3000 }),
  },
  {
    id: 'kanto-50',
    order: 2,
    name: 'Chercheur de Kanto',
    regionId: 'kanto',
    shiny: false,
    percent: 50,
    rewards: reward({
      expeditionSlots: 1,
      items: [
        { itemId: 'ultra-ball', quantity: 5 },
        { itemId: 'linking-cord', quantity: 1 },
      ],
    }),
  },
  {
    id: 'kanto-75',
    order: 3,
    name: 'Expert de Kanto',
    regionId: 'kanto',
    shiny: false,
    percent: 75,
    rewards: reward({ battleSlots: 1, daycareSlots: 1, currency: 10_000 }),
  },
  {
    id: 'kanto-100',
    order: 4,
    name: 'Maître du Pokédex de Kanto',
    regionId: 'kanto',
    shiny: false,
    percent: 100,
    rewards: reward({
      expeditionSlots: 1,
      daycareSlots: 1,
      currency: 50_000,
      items: [{ itemId: 'destiny-knot', quantity: 1 }],
    }),
  },
  {
    id: 'national-100',
    order: 0,
    name: 'Pokédex national complet',
    regionId: null,
    shiny: false,
    percent: 100,
    rewards: reward({ items: [{ itemId: 'shiny-charm', quantity: 1 }] }),
  },
  // Pokédex shiny (PLAN.md, section 2.6) : récompenses à part.
  {
    id: 'kanto-shiny-5',
    order: 10,
    name: 'Premiers éclats de Kanto',
    regionId: 'kanto',
    shiny: true,
    percent: 5,
    rewards: reward({ currency: 20_000, items: [{ itemId: 'ultra-ball', quantity: 10 }] }),
  },
  {
    id: 'kanto-shiny-25',
    order: 11,
    name: 'Chasseur chromatique de Kanto',
    regionId: 'kanto',
    shiny: true,
    percent: 25,
    rewards: reward({ currency: 100_000, bonuses: [{ type: 'capture', percent: 10 }] }),
  },
];

/** Collections thématiques : bonus permanents (PLAN.md, section 2.8). */
const collections: Collection[] = [
  {
    id: 'insectes-de-jade',
    order: 0,
    name: 'Insectes de la Forêt de Jade',
    description: 'Chenipan, Aspicot et toutes leurs évolutions.',
    speciesIds: [10, 11, 12, 13, 14, 15],
    rewards: reward({
      items: [{ itemId: 'poke-ball', quantity: 10 }],
      bonuses: [{ type: 'capture', percent: 5 }],
    }),
  },
  {
    id: 'famille-nidoran',
    order: 1,
    name: 'La famille Nidoran',
    description: 'Les deux lignées de Nidoran, jusqu’à Nidoqueen et Nidoking.',
    speciesIds: [29, 30, 31, 32, 33, 34],
    rewards: reward({ bonuses: [{ type: 'money', percent: 10 }] }),
  },
  {
    id: 'starters-de-kanto',
    order: 2,
    name: 'Starters de Kanto',
    description: 'Bulbizarre, Salamèche, Carapuce et leurs évolutions.',
    speciesIds: [1, 2, 3, 4, 5, 6, 7, 8, 9],
    rewards: reward({ expeditionSlots: 1, bonuses: [{ type: 'xp', percent: 10 }] }),
  },
];

export const seedContent: GameContentData = {
  balance: {
    expeditions: {
      initialSlots: 2,
      maxSlots: 6,
      maxTeamSize: 6,
      durationsMinutes: ALL_DURATIONS,
      encountersPerHour: 3,
      minEncounters: 1,
      lootRollsPerHour: 2,
      minLootRolls: 1,
      durationExponent: 0.9,
    },
    capture: {
      globalMultiplier: 1,
      assumedHpFraction: 0.5,
      affinityBonusPerPokemon: 0.1,
      hiddenAbilityChance: 0.05,
    },
    shiny: {
      baseRateDenominator: 4096,
      chainBonusPerExpedition: 0.25,
      chainMaxMultiplier: 3,
      chainWindowMinutes: 120,
      masudaMultiplier: 4,
    },
    pity: { weightBonusPerMiss: 0.05, maxMultiplier: 3 },
    xp: { multiplier: 1, happinessPerExpedition: 2 },
    breeding: {
      hatchMinutesPerCounter: 2,
      eggMinutes: 20,
      maxEggs: 6,
      inheritedIvCount: 3,
      hiddenAbilityInheritChance: 0.6,
      eggLevel: 1,
    },
    transfer: { candiesPerPokemon: 1, shinyBonusCandies: 10, xpPerCandy: 500 },
    daycare: { initialSlots: 1, maxSlots: 4 },
    battles: {
      initialSlots: 1,
      maxSlots: 3,
      maxTeamSize: 6,
      defaultDurationMinutes: 10,
      // ln 9 / ln 1,5 : ~90 % à PE × 1,5 et ~10 % à PE × 0,67 (PLAN.md, section 7).
      winCurveSteepness: 5.4,
      minWinChance: 0.05,
      maxWinChance: 0.95,
      typeAdvantageWeight: 0.1,
      defaultTrainerIv: 15,
      koMinutes: 60,
      cooldownMinutes: 240,
      xpMultiplier: 1,
      lossXpFraction: 0.25,
      happinessOnWin: 3,
      happinessOnLoss: -2,
    },
    evolution: { tradeItemId: 'linking-cord', dayStartHour: 6, nightStartHour: 20 },
    newPlayer: {
      starterLevel: 5,
      startingCurrency: 0,
      startingInventory: [
        { itemId: 'poke-ball', quantity: 20 },
        { itemId: 'razz-berry', quantity: 5 },
      ],
    },
  },
  regions: [
    {
      id: 'kanto',
      order: 0,
      name: 'Kanto',
      image: null,
      speciesIds: Array.from({ length: 151 }, (_, i) => i + 1),
      starterSpeciesIds: [1, 4, 7],
      unlock: { type: 'always' },
    },
  ],
  speciesOverrides: [],
  items: [
    {
      id: 'poke-ball',
      name: 'Poké Ball',
      description: 'La Ball de base.',
      icon: null,
      category: 'ball',
      rarity: 'common',
      effects: [{ type: 'ball', catchMultiplier: 1 }],
    },
    {
      id: 'great-ball',
      name: 'Super Ball',
      description: 'Plus efficace qu’une Poké Ball.',
      icon: null,
      category: 'ball',
      rarity: 'uncommon',
      effects: [{ type: 'ball', catchMultiplier: 1.5 }],
    },
    {
      id: 'ultra-ball',
      name: 'Hyper Ball',
      description: 'Plus efficace qu’une Super Ball.',
      icon: null,
      category: 'ball',
      rarity: 'rare',
      effects: [{ type: 'ball', catchMultiplier: 2 }],
    },
    {
      id: 'razz-berry',
      name: 'Baie Framby',
      description: 'Donnée au Pokémon sauvage avant le lancer : capture plus facile.',
      icon: null,
      category: 'berry',
      rarity: 'common',
      effects: [{ type: 'captureBoost', multiplier: 1.5 }],
    },
    {
      id: 'moon-stone',
      name: 'Pierre Lune',
      description: 'Fait évoluer Nidorina, Nidorino, Mélofée et Rondoudou.',
      icon: null,
      category: 'evolution',
      rarity: 'rare',
      effects: [],
    },
    {
      id: 'water-stone',
      name: 'Pierre Eau',
      description: 'Fait évoluer Têtarte, Kokiyas, Stari et Évoli.',
      icon: null,
      category: 'evolution',
      rarity: 'rare',
      effects: [],
    },
    {
      id: 'thunder-stone',
      name: 'Pierre Foudre',
      description: 'Fait évoluer Pikachu et Évoli.',
      icon: null,
      category: 'evolution',
      rarity: 'rare',
      effects: [],
    },
    {
      id: 'fire-stone',
      name: 'Pierre Feu',
      description: 'Fait évoluer Goupix, Caninos et Évoli.',
      icon: null,
      category: 'evolution',
      rarity: 'rare',
      effects: [],
    },
    {
      id: 'leaf-stone',
      name: 'Pierre Plante',
      description: 'Fait évoluer Ortide, Boustiflor et Noeunoeuf.',
      icon: null,
      category: 'evolution',
      rarity: 'rare',
      effects: [],
    },
    {
      id: 'linking-cord',
      name: 'Câble Link',
      description: 'Remplace l’échange : fait évoluer Kadabra, Machopeur, Gravalanch et Spectrum.',
      icon: null,
      category: 'evolution',
      rarity: 'epic',
      effects: [],
    },
    {
      id: 'everstone',
      name: 'Pierre Stase',
      description: 'Tenue par un parent en pension, elle transmet sa nature à l’œuf.',
      icon: null,
      category: 'breeding',
      rarity: 'rare',
      effects: [{ type: 'breedingNature', chance: 1 }],
    },
    {
      id: 'destiny-knot',
      name: 'Nœud Destin',
      description: 'Tenu par un parent en pension : l’œuf hérite de 5 IV des parents au lieu de 3.',
      icon: null,
      category: 'breeding',
      rarity: 'epic',
      effects: [{ type: 'breedingIvs', count: 5 }],
    },
    {
      id: 'shiny-charm',
      name: 'Charme Chroma',
      description:
        'Il suffit de l’avoir dans son sac : les Pokémon shiny apparaissent 3 fois plus souvent.',
      icon: null,
      category: 'endgame',
      rarity: 'legendary',
      effects: [{ type: 'shinyCharm', multiplier: 3 }],
    },
  ],
  lootTables: [
    {
      id: 'butin-route',
      name: 'Butin de route',
      entries: [
        loot('poke-ball', 0.7, 1, 3),
        loot('razz-berry', 0.25, 1, 2),
        loot('great-ball', 0.05),
      ],
    },
    {
      id: 'butin-foret',
      name: 'Butin de forêt',
      entries: [
        loot('poke-ball', 0.7, 1, 3),
        loot('razz-berry', 0.35, 1, 2),
        loot('great-ball', 0.1),
        loot('everstone', 0.02),
      ],
    },
    {
      id: 'butin-grotte',
      name: 'Butin de grotte',
      entries: [
        loot('poke-ball', 0.6, 1, 3),
        loot('great-ball', 0.2, 1, 2),
        loot('moon-stone', 0.03),
        loot('everstone', 0.04),
      ],
    },
    {
      id: 'butin-mer',
      name: 'Butin des berges',
      entries: [
        loot('poke-ball', 0.6, 2, 4),
        loot('great-ball', 0.25, 1, 2),
        loot('ultra-ball', 0.05),
        loot('water-stone', 0.03),
        loot('destiny-knot', 0.02),
      ],
    },
  ],
  zones,
  trainers,
  shopCategories,
  shopEntries,
  evolutionOverrides,
  dexMilestones,
  collections,
};
