import type {
  BattleRules,
  Encounter,
  ProgressReward,
  Quest,
  QuestCondition,
  QuestPokemon,
  QuestStep,
  Trainer,
  TrainerPokemon,
  UnlockCondition,
  Zone,
} from './schemas';

/**
 * Kanto : le parcours des 8 arènes, la Ligue, les zones spéciales et les quêtes légendaires.
 *
 * - Parcours principal : chaque badge ouvre de nouvelles zones, de plus en plus exigeantes (PE,
 *   niveaux des Pokémon sauvages). Les Champions se battent à effectif égal (taille d'équipe
 *   imposée), puis le Conseil 4 et le Maître sans restriction.
 * - Zones spéciales : ouvertes par plusieurs conditions à la fois, plus exigeantes (PE élevée,
 *   types imposés, expéditions longues). Elles abritent, rarement, des Pokémon introuvables
 *   ailleurs (Kangourex, Kicklee, Porygon, Ronflex, Lokhlass…).
 * - Quêtes : les oiseaux légendaires, Mewtwo puis Mew ; chacune ouvre sa zone en cours de route.
 *
 * Les 151 espèces sont obtenables : rencontres, évolutions (niveau, pierres de la boutique, Câble
 * Link), fossiles restaurés au Musée et quêtes. Formes alternatives : Archipel Lointain, à part.
 */

const ALL_DURATIONS = [2, 5, 15, 60, 240, 480];
const LONG_DURATIONS = [60, 240, 480];
/** Zones spéciales : pas d'aller-retour rapide. */
const SPECIAL_DURATIONS = [240, 480];

const enc = (speciesId: number, weight: number, minLevel: number, maxLevel: number): Encounter => ({
  speciesId,
  weight,
  minLevel,
  maxLevel,
});

/** Badges de Kanto uniquement (ceux des autres régions ne comptent pas). */
const badges = (count: number): UnlockCondition => ({
  type: 'badgeCount',
  count,
  regionId: 'kanto',
});
const defeated = (trainerId: string): UnlockCondition => ({ type: 'trainerDefeated', trainerId });
const allOf = (...conditions: UnlockCondition[]): UnlockCondition => ({
  type: 'allOf',
  conditions: conditions.flatMap((c) => (c.type === 'allOf' ? c.conditions : [c])),
});

const zone = (
  z: Omit<Zone, 'regionId' | 'image' | 'enabled' | 'requiredTypes' | 'durationsMinutes'> &
    Partial<Zone>,
): Zone => ({
  regionId: 'kanto',
  image: null,
  enabled: true,
  requiredTypes: [],
  durationsMinutes: ALL_DURATIONS,
  ...z,
});

export const kantoZones: Zone[] = [
  // --- Avant le premier badge -------------------------------------------------------------
  zone({
    id: 'route-1',
    order: 0,
    name: 'Route 1',
    description: 'Les hautes herbes entre Bourg Palette et Jadielle. Idéal pour débuter.',
    habitat: 'grassland',
    minPower: 0,
    affinityTypes: ['normal', 'flying'],
    encounters: [
      enc(19, 30, 2, 4),
      enc(16, 30, 2, 4),
      enc(21, 15, 3, 5),
      enc(29, 10, 3, 5),
      enc(32, 10, 3, 5),
      enc(10, 5, 3, 5),
    ],
    lootTableId: 'butin-route',
    unlock: { type: 'always' },
  }),
  zone({
    id: 'foret-de-jade',
    order: 1,
    name: 'Forêt de Jade',
    description: 'Une forêt dense où grouillent les insectes. On y aperçoit parfois un Pikachu.',
    habitat: 'forest',
    minPower: 100,
    affinityTypes: ['bug', 'grass'],
    encounters: [
      enc(10, 28, 3, 6),
      enc(13, 28, 3, 6),
      enc(11, 10, 5, 7),
      enc(14, 10, 5, 7),
      enc(16, 12, 4, 6),
      enc(43, 8, 4, 7),
      enc(25, 4, 5, 8),
    ],
    lootTableId: 'butin-foret',
    unlock: { type: 'regionDexPercent', regionId: 'kanto', percent: 3 },
  }),
  // --- Badge Roche ------------------------------------------------------------------------------
  zone({
    id: 'route-3',
    order: 2,
    name: 'Route 3',
    description: 'Un sentier escarpé au pied du Mont Sélénite, fréquenté par les Piafabec.',
    habitat: 'rough-terrain',
    minPower: 250,
    affinityTypes: ['normal', 'fighting', 'flying'],
    encounters: [
      enc(21, 28, 6, 10),
      enc(56, 20, 7, 11),
      enc(39, 14, 6, 10),
      enc(19, 14, 6, 9),
      enc(29, 12, 7, 10),
      enc(32, 12, 7, 10),
    ],
    lootTableId: 'butin-route',
    unlock: badges(1),
  }),
  zone({
    id: 'mont-selenite',
    order: 3,
    name: 'Mont Sélénite',
    description: 'Une grotte sombre, réputée pour ses météorites, ses fossiles… et ses Mélofée.',
    habitat: 'cave',
    minPower: 300,
    affinityTypes: ['rock', 'ground'],
    encounters: [
      enc(41, 38, 7, 11),
      enc(74, 28, 7, 11),
      enc(46, 14, 8, 12),
      enc(27, 12, 8, 12),
      enc(35, 8, 8, 12),
    ],
    lootTableId: 'butin-fouilles',
    unlock: badges(1),
  }),
  zone({
    id: 'pont-pepite',
    order: 4,
    name: 'Pont Pépite',
    description:
      'Le pont au nord d’Azuria et les prés de la Route 25. Un Abra s’y téléporte parfois.',
    habitat: 'grassland',
    minPower: 380,
    affinityTypes: ['grass', 'psychic'],
    encounters: [
      enc(43, 20, 10, 14),
      enc(69, 20, 10, 14),
      enc(16, 15, 11, 14),
      enc(48, 15, 11, 15),
      enc(13, 10, 9, 12),
      enc(14, 8, 10, 13),
      enc(63, 12, 10, 14),
    ],
    lootTableId: 'butin-foret',
    unlock: defeated('campeur-leo'),
  }),
  // --- Badge Cascade ----------------------------------------------------------------------------
  zone({
    id: 'cap-azuria',
    order: 5,
    name: 'Cap Azuria',
    description: 'Les berges au nord d’Azuria. Il faut au moins un Pokémon Eau pour s’y aventurer.',
    habitat: 'waters-edge',
    minPower: 480,
    requiredTypes: [{ type: 'water', count: 1 }],
    affinityTypes: ['water'],
    durationsMinutes: LONG_DURATIONS,
    encounters: [
      enc(129, 30, 10, 18),
      enc(60, 20, 12, 17),
      enc(118, 20, 12, 17),
      enc(54, 12, 13, 18),
      enc(72, 10, 13, 18),
      enc(98, 8, 13, 18),
    ],
    lootTableId: 'butin-mer',
    unlock: badges(2),
  }),
  zone({
    id: 'routes-5-6',
    order: 6,
    name: 'Routes 5 et 6',
    description: 'Les chemins qui relient Azuria à Carmin, au pied de Safrania.',
    habitat: 'grassland',
    minPower: 520,
    affinityTypes: ['normal', 'grass'],
    encounters: [
      enc(16, 20, 13, 17),
      enc(52, 18, 12, 17),
      enc(43, 15, 13, 17),
      enc(69, 15, 13, 17),
      enc(56, 12, 13, 17),
      enc(39, 10, 13, 17),
      enc(17, 4, 17, 20),
      enc(53, 3, 18, 21),
      enc(57, 3, 18, 21),
    ],
    lootTableId: 'butin-route',
    unlock: badges(2),
  }),
  zone({
    id: 'cave-taupiqueur',
    order: 7,
    name: 'Cave Taupiqueur',
    description: 'Un long tunnel creusé par des Taupiqueur, entre Carmin et Argenta.',
    habitat: 'cave',
    minPower: 560,
    affinityTypes: ['ground'],
    encounters: [enc(50, 75, 15, 22), enc(74, 15, 15, 20), enc(51, 10, 26, 31)],
    lootTableId: 'butin-grotte',
    unlock: badges(2),
  }),
  // --- Badge Foudre -----------------------------------------------------------------------------
  zone({
    id: 'routes-9-10',
    order: 8,
    name: 'Routes 9 et 10',
    description: 'Le plateau aride qui mène au Tunnel Roche et à la Centrale abandonnée.',
    habitat: 'rough-terrain',
    minPower: 800,
    affinityTypes: ['poison', 'ground', 'electric'],
    encounters: [
      enc(21, 16, 16, 22),
      enc(23, 15, 16, 22),
      enc(27, 12, 16, 22),
      enc(100, 15, 16, 22),
      enc(96, 12, 16, 22),
      enc(30, 7, 18, 22),
      enc(33, 7, 18, 22),
      enc(20, 8, 20, 24),
      enc(22, 8, 20, 24),
    ],
    lootTableId: 'butin-route',
    unlock: badges(3),
  }),
  zone({
    id: 'tunnel-roche',
    order: 9,
    name: 'Tunnel Roche',
    description: 'Un tunnel sans lumière. Mieux vaut une équipe solide pour en voir le bout.',
    habitat: 'cave',
    minPower: 850,
    affinityTypes: ['rock', 'fighting', 'ground'],
    encounters: [
      enc(41, 28, 16, 22),
      enc(74, 25, 16, 22),
      enc(66, 20, 17, 23),
      enc(56, 12, 17, 22),
      enc(95, 10, 18, 24),
      enc(42, 5, 22, 26),
    ],
    lootTableId: 'butin-grotte',
    unlock: badges(3),
  }),
  zone({
    id: 'routes-7-8',
    order: 10,
    name: 'Routes 7 et 8',
    description: 'Les routes de Céladopole et de Lavanville, où rôdent Caninos et Goupix.',
    habitat: 'grassland',
    minPower: 900,
    affinityTypes: ['fire', 'normal'],
    encounters: [
      enc(16, 15, 18, 24),
      enc(19, 12, 18, 24),
      enc(52, 15, 18, 24),
      enc(39, 10, 18, 24),
      enc(58, 12, 18, 24),
      enc(37, 12, 18, 24),
      enc(43, 8, 18, 24),
      enc(69, 8, 18, 24),
      enc(17, 4, 22, 26),
      enc(20, 4, 22, 26),
    ],
    lootTableId: 'butin-route',
    unlock: badges(3),
  }),
  // --- Badge Prisme -----------------------------------------------------------------------------
  zone({
    id: 'tour-pokemon',
    order: 11,
    name: 'Tour Pokémon',
    description: 'Le cimetière de Lavanville. Des Spectres y hantent les étages supérieurs.',
    habitat: 'urban',
    minPower: 1300,
    affinityTypes: ['ghost', 'psychic'],
    durationsMinutes: LONG_DURATIONS,
    encounters: [
      enc(92, 60, 22, 29),
      enc(104, 25, 22, 28),
      enc(93, 10, 25, 30),
      enc(105, 5, 28, 32),
    ],
    lootTableId: 'butin-grotte',
    unlock: badges(4),
  }),
  zone({
    id: 'routes-12-15',
    order: 12,
    name: 'Routes 12 à 15',
    description: 'Le Pont Silence et les sentiers fleuris qui descendent vers Parmanie.',
    habitat: 'grassland',
    minPower: 1400,
    affinityTypes: ['grass', 'bug', 'normal'],
    durationsMinutes: LONG_DURATIONS,
    encounters: [
      enc(43, 14, 22, 28),
      enc(69, 14, 22, 28),
      enc(48, 12, 24, 28),
      enc(16, 10, 23, 27),
      enc(44, 8, 26, 30),
      enc(70, 8, 26, 30),
      enc(17, 8, 26, 30),
      enc(49, 6, 27, 31),
      enc(83, 6, 24, 28),
      enc(132, 4, 24, 28),
    ],
    lootTableId: 'butin-foret',
    unlock: badges(4),
  }),
  zone({
    id: 'piste-cyclable',
    order: 13,
    name: 'Piste Cyclable',
    description: 'Les Routes 16 à 18, longue descente vers Parmanie prisée des motards.',
    habitat: 'urban',
    minPower: 1500,
    affinityTypes: ['flying', 'poison', 'normal'],
    durationsMinutes: LONG_DURATIONS,
    encounters: [
      enc(84, 28, 22, 28),
      enc(21, 16, 22, 28),
      enc(19, 10, 22, 28),
      enc(88, 10, 24, 28),
      enc(109, 10, 24, 28),
      enc(22, 10, 25, 30),
      enc(20, 8, 25, 30),
      enc(85, 4, 28, 32),
      enc(53, 4, 28, 32),
    ],
    lootTableId: 'butin-route',
    unlock: badges(4),
  }),
  // --- Badge Âme ------------------------------------------------------------------------------------
  zone({
    id: 'routes-maritimes',
    order: 14,
    name: 'Routes maritimes',
    description: 'Les Routes 19 à 21, en pleine mer. Il faut deux Pokémon Eau pour nager si loin.',
    habitat: 'sea',
    minPower: 2000,
    requiredTypes: [{ type: 'water', count: 2 }],
    affinityTypes: ['water'],
    durationsMinutes: LONG_DURATIONS,
    encounters: [
      enc(72, 26, 28, 36),
      enc(116, 14, 28, 34),
      enc(90, 10, 28, 34),
      enc(120, 10, 28, 34),
      enc(118, 8, 28, 34),
      enc(129, 8, 25, 35),
      enc(98, 6, 28, 34),
      enc(86, 5, 30, 36),
      enc(73, 5, 34, 40),
      enc(119, 3, 34, 40),
      enc(117, 3, 34, 40),
      enc(99, 2, 34, 40),
    ],
    lootTableId: 'butin-mer',
    unlock: badges(5),
  }),
  // --- Badge Marais -----------------------------------------------------------------------------
  zone({
    id: 'manoir-pokemon',
    order: 15,
    name: 'Manoir Pokémon',
    description:
      'Les ruines d’un laboratoire de Cramois’Île. Des expériences y auraient mal tourné.',
    habitat: 'urban',
    minPower: 2400,
    affinityTypes: ['fire', 'poison'],
    durationsMinutes: LONG_DURATIONS,
    encounters: [
      enc(109, 18, 30, 36),
      enc(88, 18, 30, 36),
      enc(58, 12, 30, 36),
      enc(37, 12, 30, 36),
      enc(77, 10, 32, 38),
      enc(20, 10, 32, 38),
      enc(132, 8, 30, 36),
      enc(110, 6, 34, 40),
      enc(89, 6, 34, 40),
    ],
    lootTableId: 'butin-grotte',
    unlock: badges(6),
  }),
  // --- Badge Volcan -----------------------------------------------------------------------------
  zone({
    id: 'route-23',
    order: 16,
    name: 'Route 23',
    description: 'La route des badges, gardée par des dresseurs qui vérifient chaque insigne.',
    habitat: 'grassland',
    minPower: 2800,
    affinityTypes: ['normal', 'fighting', 'poison'],
    durationsMinutes: LONG_DURATIONS,
    encounters: [
      enc(22, 18, 38, 44),
      enc(57, 18, 38, 44),
      enc(24, 16, 38, 44),
      enc(28, 16, 38, 44),
      enc(20, 12, 38, 44),
      enc(85, 10, 40, 45),
      enc(47, 10, 40, 45),
    ],
    lootTableId: 'butin-route',
    unlock: badges(7),
  }),
  // --- Badge Terre --------------------------------------------------------------------------------
  zone({
    id: 'route-victoire',
    order: 17,
    name: 'Route Victoire',
    description: 'La grotte qui mène à la Ligue Pokémon. Seuls les dresseurs aguerris en sortent.',
    habitat: 'cave',
    minPower: 3200,
    affinityTypes: ['fighting', 'rock', 'ground'],
    durationsMinutes: LONG_DURATIONS,
    encounters: [
      enc(67, 18, 42, 48),
      enc(75, 18, 42, 48),
      enc(95, 14, 42, 48),
      enc(42, 14, 42, 48),
      enc(66, 12, 40, 44),
      enc(74, 10, 40, 44),
      enc(105, 8, 44, 48),
      enc(41, 6, 40, 44),
    ],
    lootTableId: 'butin-elite',
    unlock: badges(8),
  }),

  // === Zones spéciales : plusieurs conditions, PE élevée, Pokémon exclusifs (rares) ===========
  zone({
    id: 'reserve-chen',
    order: 18,
    name: 'Réserve du Prof. Chen',
    description:
      'Le Prof. Chen y étudie des Pokémon rares, dont Bulbizarre, Salamèche, Carapuce et Évoli. Il n’en ouvre l’accès qu’aux dresseurs confirmés.',
    habitat: 'grassland',
    minPower: 1000,
    affinityTypes: ['grass', 'fire', 'water'],
    durationsMinutes: SPECIAL_DURATIONS,
    encounters: [
      enc(16, 26, 12, 16),
      enc(19, 26, 12, 16),
      enc(29, 12, 12, 16),
      enc(32, 12, 12, 16),
      enc(39, 12, 12, 16),
      enc(1, 3, 10, 12),
      enc(4, 3, 10, 12),
      enc(7, 3, 10, 12),
      enc(133, 3, 10, 12),
    ],
    lootTableId: 'butin-foret',
    unlock: allOf(badges(2), { type: 'regionDexPercent', regionId: 'kanto', percent: 20 }),
  }),
  zone({
    id: 'ronflex-endormi',
    order: 19,
    name: 'Ronflex endormi',
    description:
      'Un Ronflex bloque la Route 12. Le réveiller demande de la force : un Pokémon Combat est indispensable. Un Excelangue rôde dans les parages.',
    habitat: 'mountain',
    minPower: 2000,
    requiredTypes: [{ type: 'fighting', count: 1 }],
    affinityTypes: ['fighting', 'normal'],
    durationsMinutes: SPECIAL_DURATIONS,
    encounters: [
      enc(43, 18, 26, 30),
      enc(69, 18, 26, 30),
      enc(17, 16, 28, 32),
      enc(44, 14, 28, 32),
      enc(70, 14, 28, 32),
      enc(143, 4, 30, 30),
      enc(108, 4, 28, 32),
    ],
    lootTableId: 'butin-elite',
    unlock: allOf(badges(4), { type: 'speciesCaught', count: 45 }),
  }),
  zone({
    id: 'parc-safari',
    order: 20,
    name: 'Parc Safari',
    description:
      'La réserve de Parmanie. Ses Pokémon farouches ne se montrent qu’aux dresseurs patients : Kangourex, Tauros, Leveinard, Minidraco…',
    habitat: 'grassland',
    minPower: 2400,
    affinityTypes: ['normal', 'bug', 'grass', 'ground'],
    durationsMinutes: SPECIAL_DURATIONS,
    encounters: [
      enc(111, 14, 25, 32),
      enc(102, 14, 25, 32),
      enc(114, 10, 25, 32),
      enc(48, 10, 25, 32),
      enc(84, 8, 25, 32),
      enc(30, 7, 28, 33),
      enc(33, 7, 28, 33),
      enc(46, 6, 25, 30),
      enc(47, 4, 30, 34),
      enc(49, 4, 30, 34),
      enc(115, 3, 25, 32),
      enc(128, 3, 25, 32),
      enc(123, 3, 25, 32),
      enc(127, 3, 25, 32),
      enc(113, 1.5, 25, 32),
      enc(147, 1.5, 15, 25),
    ],
    lootTableId: 'butin-foret',
    unlock: allOf(badges(5), { type: 'speciesCaught', count: 60 }),
  }),
  zone({
    id: 'dojo-karate',
    order: 21,
    name: 'Dojo Karaté',
    description:
      'Le dojo voisin de l’arène de Safrania. Seule une équipe d’au moins deux Pokémon Combat y est admise ; les disciples du maître, Kicklee et Tygnon, s’y entraînent.',
    habitat: 'urban',
    minPower: 2600,
    requiredTypes: [{ type: 'fighting', count: 2 }],
    affinityTypes: ['fighting'],
    durationsMinutes: SPECIAL_DURATIONS,
    encounters: [
      enc(56, 30, 30, 36),
      enc(66, 30, 30, 36),
      enc(57, 15, 34, 40),
      enc(67, 15, 34, 40),
      enc(106, 5, 30, 35),
      enc(107, 5, 30, 35),
    ],
    lootTableId: 'butin-elite',
    unlock: allOf(badges(5), defeated('karateka-kiyo')),
  }),
  zone({
    id: 'sylphe-sarl',
    order: 22,
    name: 'Sylphe SARL',
    description:
      'Le siège de Sylphe SARL, libéré de la Team Rocket. Ses laboratoires cachent un Porygon et un M. Mime évadé. Un Pokémon Psy aide à se repérer entre les téléporteurs.',
    habitat: 'urban',
    minPower: 3000,
    requiredTypes: [{ type: 'psychic', count: 1 }],
    affinityTypes: ['electric', 'psychic', 'poison'],
    durationsMinutes: SPECIAL_DURATIONS,
    encounters: [
      enc(81, 16, 32, 38),
      enc(100, 16, 32, 38),
      enc(109, 14, 32, 38),
      enc(96, 14, 32, 38),
      enc(63, 10, 32, 36),
      enc(82, 7, 38, 42),
      enc(101, 7, 38, 42),
      enc(97, 6, 38, 42),
      enc(64, 4, 38, 42),
      enc(137, 3, 30, 35),
      enc(122, 3, 32, 38),
    ],
    lootTableId: 'butin-elite',
    unlock: allOf(badges(6), defeated('sbire-rocket'), { type: 'speciesCaught', count: 70 }),
  }),

  // === Zones de quêtes : ouvertes en cours de quête ==============================================
  zone({
    id: 'centrale',
    order: 23,
    name: 'Centrale',
    description:
      'Une centrale électrique abandonnée où crépitent les Pokémon Électrik. Un Élektek y rôde.',
    habitat: 'urban',
    minPower: 1800,
    affinityTypes: ['electric'],
    durationsMinutes: SPECIAL_DURATIONS,
    encounters: [
      enc(100, 26, 28, 34),
      enc(81, 26, 28, 34),
      enc(25, 16, 28, 32),
      enc(82, 10, 32, 36),
      enc(101, 10, 32, 36),
      enc(26, 4, 34, 38),
      enc(125, 4, 32, 36),
    ],
    lootTableId: 'butin-grotte',
    unlock: { type: 'questStepsDone', questId: 'electhor', count: 1 },
  }),
  zone({
    id: 'iles-ecume',
    order: 24,
    name: 'Îles Écume',
    description:
      'Deux îles glacées au large de Parmanie. Un oiseau légendaire y aurait son nid ; Lokhlass et Lippoutou y vivent cachés.',
    habitat: 'sea',
    minPower: 2600,
    requiredTypes: [{ type: 'water', count: 2 }],
    affinityTypes: ['ice', 'water'],
    durationsMinutes: SPECIAL_DURATIONS,
    encounters: [
      enc(86, 24, 32, 38),
      enc(90, 18, 32, 38),
      enc(79, 16, 32, 38),
      enc(54, 12, 32, 38),
      enc(87, 8, 36, 42),
      enc(91, 4, 38, 42),
      enc(80, 6, 36, 42),
      enc(55, 6, 36, 42),
      enc(124, 3, 34, 38),
      enc(131, 3, 34, 40),
    ],
    lootTableId: 'butin-mer',
    unlock: { type: 'questStepsDone', questId: 'artikodin', count: 1 },
  }),
  zone({
    id: 'mont-braise',
    order: 25,
    name: 'Mont Braise',
    description:
      'Un volcan des Îles Sevii. La lave y garde au chaud un oiseau de feu… et un Magmar.',
    habitat: 'mountain',
    minPower: 3000,
    requiredTypes: [{ type: 'fire', count: 1 }],
    affinityTypes: ['fire', 'rock'],
    durationsMinutes: SPECIAL_DURATIONS,
    encounters: [
      enc(77, 22, 36, 42),
      enc(74, 16, 36, 40),
      enc(66, 14, 36, 40),
      enc(58, 12, 36, 42),
      enc(37, 12, 36, 42),
      enc(75, 8, 38, 44),
      enc(78, 6, 40, 45),
      enc(67, 6, 40, 45),
      enc(126, 4, 38, 42),
    ],
    lootTableId: 'butin-fouilles',
    unlock: { type: 'questStepsDone', questId: 'sulfura', count: 1 },
  }),
  zone({
    id: 'grotte-azuree',
    order: 26,
    name: 'Grotte Azurée',
    description: 'La caverne interdite d’Azuria, peuplée de Pokémon redoutables.',
    habitat: 'cave',
    minPower: 4500,
    affinityTypes: ['psychic', 'ground'],
    durationsMinutes: SPECIAL_DURATIONS,
    encounters: [
      enc(42, 12, 52, 58),
      enc(47, 12, 52, 58),
      enc(57, 10, 52, 58),
      enc(64, 10, 52, 58),
      enc(82, 10, 52, 58),
      enc(101, 10, 52, 58),
      enc(112, 10, 55, 60),
      enc(132, 10, 52, 58),
      enc(55, 8, 55, 60),
      enc(26, 4, 55, 60),
      enc(40, 4, 55, 60),
    ],
    lootTableId: 'butin-elite',
    unlock: { type: 'questStepsDone', questId: 'mewtwo', count: 3 },
  }),
  zone({
    id: 'ile-lointaine',
    order: 27,
    name: 'Île Lointaine',
    description: 'Une île couverte de hautes herbes, absente des cartes. Quelque chose y joue…',
    habitat: 'grassland',
    minPower: 3600,
    affinityTypes: ['grass', 'bug', 'psychic'],
    durationsMinutes: SPECIAL_DURATIONS,
    encounters: [
      enc(114, 20, 45, 50),
      enc(102, 20, 45, 50),
      enc(48, 18, 45, 50),
      enc(46, 14, 45, 50),
      enc(49, 10, 48, 52),
      enc(103, 6, 50, 55),
      enc(47, 6, 48, 52),
      enc(123, 3, 48, 52),
      enc(127, 3, 48, 52),
    ],
    lootTableId: 'butin-foret',
    unlock: { type: 'questStepsDone', questId: 'mew', count: 2 },
  }),
];

// --- Dresseurs ---------------------------------------------------------------------------------

const mon = (speciesId: number, level: number, iv: number | null = null): TrainerPokemon => ({
  speciesId,
  level,
  iv,
  nature: null,
});
const noRules = (): BattleRules => ({
  teamSize: null,
  maxLevel: null,
  requiredTypes: [],
  forbiddenTypes: [],
  minPower: 0,
});
/** Sprites de dresseurs servis par l'API (`pnpm sprites:download`, source : Pokémon Showdown). */
const sprite = (name: string) => `/api/sprites/trainers/${name}.png`;

/** Dresseur de route : répétable, rapporte de l'argent et du butin. */
const trainer = (
  t: Pick<Trainer, 'id' | 'zoneId' | 'order' | 'name' | 'trainerClass' | 'team' | 'unlock'> &
    Partial<Trainer> & { spriteName: string },
): Trainer => {
  const { spriteName, ...rest } = t;
  return {
    regionId: 'kanto',
    sprite: sprite(spriteName),
    durationMinutes: null,
    rules: noRules(),
    money: 0,
    lootTableId: 'butin-route',
    lootRolls: 1,
    badge: null,
    repeatable: true,
    cooldownMinutes: null,
    koMinutes: null,
    enabled: true,
    ...rest,
  };
};

/**
 * Champion d'arène : unique, combat à effectif égal (autant de Pokémon que lui), badge.
 * PE minimale ≈ 55 à 60 % de la sienne, pour éviter les combats perdus d'avance.
 */
const gymLeader = (
  id: string,
  order: number,
  name: string,
  trainerClass: string,
  spriteName: string,
  badge: string,
  team: TrainerPokemon[],
  unlock: UnlockCondition,
  extra: Partial<Trainer> & { minPower: number },
): Trainer => {
  const { minPower, ...rest } = extra;
  return trainer({
    id,
    zoneId: null,
    order,
    name,
    trainerClass,
    spriteName,
    team,
    unlock,
    durationMinutes: 60,
    rules: { ...noRules(), teamSize: team.length, minPower },
    money: Math.max(...team.map((m) => m.level)) * 100,
    lootTableId: 'butin-grotte',
    lootRolls: 3,
    badge: { name: badge, image: null },
    repeatable: false,
    koMinutes: 120,
    ...rest,
  });
};

const GYM = 'Champion d’arène';
const GYM_F = 'Championne d’arène';

export const kantoTrainers: Trainer[] = [
  // Avant le Badge Roche
  trainer({
    id: 'gamin-tom',
    zoneId: 'route-1',
    order: 0,
    name: 'Tom',
    trainerClass: 'Gamin',
    spriteName: 'youngster',
    team: [mon(19, 4)],
    durationMinutes: 10,
    money: 80,
    unlock: { type: 'always' },
  }),
  trainer({
    id: 'fillette-lise',
    zoneId: 'route-1',
    order: 1,
    name: 'Lise',
    trainerClass: 'Fillette',
    spriteName: 'lass',
    team: [mon(16, 4), mon(29, 5)],
    durationMinutes: 15,
    money: 120,
    unlock: defeated('gamin-tom'),
  }),
  trainer({
    id: 'scout-rick',
    zoneId: 'foret-de-jade',
    order: 2,
    name: 'Rick',
    trainerClass: 'Scout',
    spriteName: 'bugcatcher',
    team: [mon(10, 6), mon(13, 6), mon(14, 7)],
    durationMinutes: 20,
    money: 180,
    lootTableId: 'butin-foret',
    lootRolls: 2,
    unlock: { type: 'regionDexPercent', regionId: 'kanto', percent: 3 },
  }),
  gymLeader(
    'pierre',
    3,
    'Pierre',
    GYM,
    'brock',
    'Badge Roche',
    [mon(74, 12), mon(95, 14)],
    defeated('scout-rick'),
    { minPower: 150, koMinutes: null },
  ),
  // Badge Roche → Badge Cascade
  trainer({
    id: 'campeur-leo',
    zoneId: 'mont-selenite',
    order: 4,
    name: 'Léo',
    trainerClass: 'Campeur',
    spriteName: 'camper',
    team: [mon(27, 10), mon(23, 11)],
    durationMinutes: 30,
    rules: { ...noRules(), maxLevel: 15 },
    money: 300,
    lootTableId: 'butin-grotte',
    lootRolls: 2,
    unlock: badges(1),
  }),
  trainer({
    id: 'intello-miguel',
    zoneId: 'mont-selenite',
    order: 5,
    name: 'Miguel',
    trainerClass: 'Intello',
    spriteName: 'supernerd',
    team: [mon(88, 12), mon(100, 12), mon(109, 12)],
    durationMinutes: 30,
    money: 360,
    lootTableId: 'butin-fouilles',
    lootRolls: 2,
    unlock: defeated('campeur-leo'),
  }),
  trainer({
    id: 'pique-niqueuse-ali',
    zoneId: 'pont-pepite',
    order: 6,
    name: 'Ali',
    trainerClass: 'Pique-niqueuse',
    spriteName: 'picnicker',
    team: [mon(43, 14), mon(69, 14), mon(16, 15)],
    durationMinutes: 30,
    money: 420,
    lootTableId: 'butin-foret',
    lootRolls: 2,
    unlock: defeated('intello-miguel'),
  }),
  gymLeader(
    'ondine',
    7,
    'Ondine',
    GYM_F,
    'misty',
    'Badge Cascade',
    [mon(120, 18), mon(121, 21)],
    defeated('pique-niqueuse-ali'),
    { minPower: 280, lootTableId: 'butin-mer' },
  ),
  // Badge Cascade → Badge Foudre
  trainer({
    id: 'marin-hugo',
    zoneId: 'cap-azuria',
    order: 8,
    name: 'Hugo',
    trainerClass: 'Marin',
    spriteName: 'sailor',
    team: [mon(72, 18), mon(66, 18), mon(98, 20)],
    durationMinutes: 45,
    money: 600,
    lootTableId: 'butin-mer',
    lootRolls: 2,
    unlock: badges(2),
  }),
  gymLeader(
    'major-bob',
    9,
    'Major Bob',
    GYM,
    'ltsurge',
    'Badge Foudre',
    [mon(100, 21), mon(25, 18), mon(26, 24)],
    defeated('marin-hugo'),
    { minPower: 420 },
  ),
  // Badge Foudre → Badge Prisme
  trainer({
    id: 'montagnard-ivan',
    zoneId: 'tunnel-roche',
    order: 10,
    name: 'Ivan',
    trainerClass: 'Montagnard',
    spriteName: 'hiker-gen3',
    team: [mon(74, 20), mon(66, 21), mon(95, 22), mon(75, 24)],
    durationMinutes: 45,
    money: 900,
    lootTableId: 'butin-grotte',
    lootRolls: 2,
    unlock: badges(3),
  }),
  gymLeader(
    'erika',
    11,
    'Erika',
    GYM_F,
    'erika',
    'Badge Prisme',
    [mon(71, 29), mon(114, 24), mon(45, 29)],
    defeated('montagnard-ivan'),
    { minPower: 600, lootTableId: 'butin-foret' },
  ),
  // Badge Prisme → Badge Âme
  trainer({
    id: 'mediume-paula',
    zoneId: 'tour-pokemon',
    order: 12,
    name: 'Paula',
    trainerClass: 'Médium',
    spriteName: 'channeler-gen3',
    team: [mon(92, 26), mon(92, 26), mon(104, 27), mon(93, 28)],
    durationMinutes: 60,
    money: 1100,
    lootTableId: 'butin-grotte',
    lootRolls: 2,
    unlock: badges(4),
  }),
  trainer({
    id: 'motard-rex',
    zoneId: 'piste-cyclable',
    order: 13,
    name: 'Rex',
    trainerClass: 'Motard',
    spriteName: 'biker',
    team: [mon(109, 28), mon(88, 28), mon(110, 30), mon(89, 30)],
    durationMinutes: 60,
    money: 1300,
    lootRolls: 2,
    unlock: defeated('mediume-paula'),
  }),
  gymLeader(
    'koga',
    14,
    'Koga',
    GYM,
    'koga',
    'Badge Âme',
    [mon(109, 37, 18), mon(89, 39, 18), mon(109, 37, 18), mon(110, 43, 18)],
    defeated('motard-rex'),
    { minPower: 1050, durationMinutes: 90 },
  ),
  // Badge Âme → Badge Marais
  trainer({
    id: 'karateka-kiyo',
    zoneId: null,
    order: 15,
    name: 'Kiyo',
    trainerClass: 'Maître Karaté',
    spriteName: 'blackbelt',
    team: [mon(106, 37), mon(107, 37), mon(57, 38), mon(68, 40)],
    durationMinutes: 90,
    money: 2500,
    lootTableId: 'butin-elite',
    lootRolls: 2,
    repeatable: false,
    koMinutes: 120,
    unlock: badges(5),
  }),
  trainer({
    id: 'sbire-rocket',
    zoneId: null,
    order: 16,
    name: 'Sbire',
    trainerClass: 'Team Rocket',
    spriteName: 'rocketgrunt',
    team: [mon(24, 36), mon(42, 36), mon(110, 38), mon(53, 38)],
    durationMinutes: 60,
    money: 1800,
    lootTableId: 'butin-grotte',
    lootRolls: 2,
    unlock: badges(5),
  }),
  gymLeader(
    'morgane',
    17,
    'Morgane',
    GYM_F,
    'sabrina',
    'Badge Marais',
    [mon(64, 38, 20), mon(122, 37, 20), mon(49, 38, 20), mon(65, 43, 20)],
    defeated('sbire-rocket'),
    { minPower: 1100, durationMinutes: 90 },
  ),
  // Badge Marais → Badge Volcan
  trainer({
    id: 'nageuse-lena',
    zoneId: 'routes-maritimes',
    order: 18,
    name: 'Léna',
    trainerClass: 'Nageuse',
    spriteName: 'swimmerf',
    team: [mon(120, 37), mon(117, 38), mon(119, 38), mon(121, 40)],
    durationMinutes: 60,
    money: 1600,
    lootTableId: 'butin-mer',
    lootRolls: 2,
    unlock: badges(6),
  }),
  gymLeader(
    'auguste',
    19,
    'Auguste',
    GYM,
    'blaine',
    'Badge Volcan',
    [mon(58, 42, 22), mon(77, 40, 22), mon(78, 42, 22), mon(59, 47, 22)],
    defeated('nageuse-lena'),
    { minPower: 1250, durationMinutes: 90 },
  ),
  // Badge Volcan → Badge Terre
  trainer({
    id: 'scientifique-hector',
    zoneId: 'manoir-pokemon',
    order: 20,
    name: 'Hector',
    trainerClass: 'Scientifique',
    spriteName: 'scientist',
    team: [mon(101, 42), mon(82, 42), mon(89, 43), mon(110, 44), mon(137, 44)],
    durationMinutes: 60,
    money: 2200,
    lootTableId: 'butin-grotte',
    lootRolls: 2,
    unlock: badges(7),
  }),
  gymLeader(
    'giovanni',
    21,
    'Giovanni',
    GYM,
    'giovanni',
    'Badge Terre',
    [mon(111, 45, 25), mon(51, 42, 25), mon(31, 44, 25), mon(34, 45, 25), mon(112, 50, 25)],
    defeated('scientifique-hector'),
    { minPower: 1650, durationMinutes: 120, koMinutes: 180, lootTableId: 'butin-elite' },
  ),
  // Route Victoire, puis la Ligue
  trainer({
    id: 'topdresseuse-alice',
    zoneId: 'route-victoire',
    order: 22,
    name: 'Alice',
    trainerClass: 'Topdresseuse',
    spriteName: 'acetrainerf',
    team: [mon(112, 48, 20), mon(26, 47, 20), mon(62, 48, 20), mon(121, 48, 20), mon(36, 47, 20)],
    durationMinutes: 90,
    money: 3500,
    lootTableId: 'butin-elite',
    lootRolls: 2,
    unlock: badges(8),
  }),
  ...league(),
];

/** Conseil 4 puis Maître de la Ligue : uniques, à affronter dans l'ordre, IV élevés. */
function league(): Trainer[] {
  const member = (
    id: string,
    order: number,
    name: string,
    spriteName: string,
    team: TrainerPokemon[],
    unlock: UnlockCondition,
    extra: Partial<Trainer> = {},
  ): Trainer =>
    trainer({
      id,
      zoneId: null,
      order,
      name,
      trainerClass: 'Conseil 4',
      spriteName,
      team,
      unlock,
      durationMinutes: 120,
      money: 6000,
      lootTableId: 'butin-elite',
      lootRolls: 3,
      repeatable: false,
      koMinutes: 240,
      ...extra,
    });
  return [
    member(
      'olga',
      23,
      'Olga',
      'lorelei-gen3',
      [mon(87, 54, 25), mon(91, 53, 25), mon(80, 54, 25), mon(124, 56, 25), mon(131, 56, 25)],
      allOf(badges(8), defeated('topdresseuse-alice')),
    ),
    member(
      'aldo',
      24,
      'Aldo',
      'bruno',
      [mon(95, 53, 25), mon(107, 55, 25), mon(106, 55, 25), mon(95, 56, 25), mon(68, 58, 25)],
      defeated('olga'),
    ),
    member(
      'agatha',
      25,
      'Agatha',
      'agatha-gen3',
      [mon(94, 56, 25), mon(42, 56, 25), mon(93, 55, 25), mon(24, 58, 25), mon(94, 60, 25)],
      defeated('aldo'),
    ),
    member(
      'peter',
      26,
      'Peter',
      'lance',
      [mon(130, 56, 25), mon(148, 54, 25), mon(148, 54, 25), mon(142, 58, 25), mon(149, 60, 25)],
      defeated('agatha'),
    ),
    member(
      'maitre-blue',
      27,
      'Blue',
      'blue',
      [
        mon(18, 61, 31),
        mon(65, 59, 31),
        mon(112, 61, 31),
        mon(103, 61, 31),
        mon(130, 63, 31),
        mon(6, 65, 31),
      ],
      defeated('peter'),
      { trainerClass: 'Maître de la Ligue', durationMinutes: 180, money: 15_000, lootRolls: 5 },
    ),
  ];
}

// --- Quêtes légendaires --------------------------------------------------------------------------

const reward = (r: Partial<ProgressReward>): ProgressReward => ({
  currency: 0,
  items: [],
  expeditionSlots: 0,
  battleSlots: 0,
  daycareSlots: 0,
  bonuses: [],
  ...r,
});
/** Pokémon offert par une quête : au moins 3 IV parfaits, comme dans les jeux récents. */
const legendary = (speciesId: number, level: number): QuestPokemon => ({
  speciesId,
  level,
  perfectIvs: 3,
});
const step = (name: string, description: string, condition: QuestCondition): QuestStep => ({
  name,
  description,
  condition,
});
const catchOf = (count: number, pokemonType: string | null): QuestCondition => ({
  type: 'catchPokemon',
  count,
  pokemonType,
  speciesId: null,
});
/** Expédition réussie dans une zone de quête, avec des Pokémon d'un type et d'une PE donnés. */
const questExpedition = (
  zoneId: string,
  memberType: string | null,
  memberCount: number,
  minMemberPower: number,
  count = 1,
): QuestCondition => ({
  type: 'expedition',
  zoneId,
  count,
  memberType,
  memberCount,
  minMemberPower,
});

/** Quêtes des légendaires de Kanto : la première étape ouvre la zone de la quête. */
export const kantoQuests: Quest[] = [
  {
    id: 'artikodin',
    order: 1,
    name: 'L’oiseau des glaces',
    description: 'Un oiseau légendaire ferait tomber la neige sur les Îles Écume.',
    image: null,
    regionId: 'kanto',
    enabled: true,
    unlock: badges(5),
    steps: [
      step(
        'Les pieds dans l’eau',
        'Capture 15 Pokémon Eau pour préparer la traversée.',
        catchOf(15, 'water'),
      ),
      step('Le froid des îles', 'Capture 5 Pokémon Glace aux Îles Écume.', catchOf(5, 'ice')),
      step(
        'Le nid d’Artikodin',
        'Réussis une expédition aux Îles Écume avec 2 Pokémon Glace de PE 450 ou plus.',
        questExpedition('iles-ecume', 'ice', 2, 450),
      ),
    ],
    rewards: {
      ...reward({ currency: 10_000, items: [{ itemId: 'bottle-cap', quantity: 1 }] }),
      pokemon: [legendary(144, 50)],
    },
  },
  {
    id: 'electhor',
    order: 0,
    name: 'L’oiseau de foudre',
    description: 'Des éclairs zèbrent le ciel au-dessus de la Centrale abandonnée.',
    image: null,
    regionId: 'kanto',
    enabled: true,
    unlock: badges(4),
    steps: [
      step(
        'Haute tension',
        'Capture 10 Pokémon Électrik pour trouver l’entrée de la Centrale.',
        catchOf(10, 'electric'),
      ),
      step('Courts-circuits', 'Capture 8 Pokémon Électrik à la Centrale.', catchOf(8, 'electric')),
      step('Prouver sa valeur', 'Bats Koga, le Champion de Parmanie.', defeated('koga')),
      step(
        'Le cœur de la Centrale',
        'Réussis une expédition à la Centrale avec 2 Pokémon Électrik de PE 350 ou plus.',
        questExpedition('centrale', 'electric', 2, 350),
      ),
    ],
    rewards: {
      ...reward({ currency: 10_000, items: [{ itemId: 'bottle-cap', quantity: 1 }] }),
      pokemon: [legendary(145, 50)],
    },
  },
  {
    id: 'sulfura',
    order: 2,
    name: 'L’oiseau de feu',
    description: 'Le Mont Braise gronde : un oiseau de flammes y aurait été aperçu.',
    image: null,
    regionId: 'kanto',
    enabled: true,
    unlock: badges(7),
    steps: [
      step('Explorateur', 'Capture 80 espèces différentes.', { type: 'speciesCaught', count: 80 }),
      step('Coulées de lave', 'Capture 8 Pokémon Feu au Mont Braise.', catchOf(8, 'fire')),
      step(
        'Le sommet du volcan',
        'Réussis une expédition au Mont Braise avec 2 Pokémon Feu de PE 500 ou plus.',
        questExpedition('mont-braise', 'fire', 2, 500),
      ),
    ],
    rewards: {
      ...reward({ currency: 10_000, items: [{ itemId: 'bottle-cap', quantity: 1 }] }),
      pokemon: [legendary(146, 50)],
    },
  },
  {
    id: 'mewtwo',
    order: 3,
    name: 'Le Pokémon génétique',
    description:
      'Une créature née d’expériences interdites se cacherait au fond de la Grotte Azurée.',
    image: null,
    regionId: 'kanto',
    enabled: true,
    unlock: badges(8),
    steps: [
      step('Maître de la Ligue', 'Bats le Maître de la Ligue Pokémon.', defeated('maitre-blue')),
      step(
        'Les trois oiseaux',
        'Termine les quêtes d’Artikodin, d’Électhor et de Sulfura.',
        allOf(
          { type: 'questCompleted', questId: 'artikodin' },
          { type: 'questCompleted', questId: 'electhor' },
          { type: 'questCompleted', questId: 'sulfura' },
        ),
      ),
      step('Chercheur', 'Capture 80 % du Pokédex de Kanto.', {
        type: 'regionDexPercent',
        regionId: 'kanto',
        percent: 80,
      }),
      step(
        'La Grotte Azurée',
        'Réussis une expédition dans la Grotte Azurée avec 3 Pokémon de PE 750 ou plus.',
        questExpedition('grotte-azuree', null, 3, 750),
      ),
    ],
    rewards: {
      ...reward({ currency: 50_000, items: [{ itemId: 'gold-bottle-cap', quantity: 1 }] }),
      pokemon: [legendary(150, 70)],
    },
  },
  {
    id: 'mew',
    order: 4,
    name: 'Le Pokémon fabuleux',
    description: 'Mewtwo n’est qu’une copie. L’original jouerait sur une île absente des cartes.',
    image: null,
    regionId: 'kanto',
    enabled: true,
    unlock: { type: 'questCompleted', questId: 'mewtwo' },
    steps: [
      step('Origines', 'Fais éclore 20 œufs.', { type: 'eggsHatched', count: 20 }),
      step('Presque complet', 'Capture 95 % du Pokédex de Kanto.', {
        type: 'regionDexPercent',
        regionId: 'kanto',
        percent: 95,
      }),
      step('Grand collectionneur', 'Capture 30 Pokémon.', catchOf(30, null)),
      step(
        'Les hautes herbes',
        'Réussis 3 expéditions sur l’Île Lointaine.',
        questExpedition('ile-lointaine', null, 0, 0, 3),
      ),
    ],
    rewards: {
      ...reward({ items: [{ itemId: 'ability-patch', quantity: 1 }] }),
      pokemon: [legendary(151, 30)],
    },
  },
];
