-- Johto refait : parcours des 8 arènes, Ligue, zones spéciales (conditions combinées, Pokémon
-- exclusifs) et quêtes légendaires ; région activée, avec ses légendaires et ses starters.
-- Généré depuis le seed (packages/content/src/seed-johto.ts). Ajouts sans écraser l’existant ;
-- les entités de Johto déjà présentes ne sont modifiées que si elles n’ont pas été retouchées.
UPDATE "zones" SET "description" = 'Le chemin herbeux qui relie Bourg Geon à Ville Griotte. Idéal pour débuter.', "encounters" = '[{"speciesId":161,"weight":30,"minLevel":2,"maxLevel":4},{"speciesId":163,"weight":25,"minLevel":2,"maxLevel":4},{"speciesId":187,"weight":15,"minLevel":3,"maxLevel":5},{"speciesId":16,"weight":15,"minLevel":2,"maxLevel":4},{"speciesId":19,"weight":15,"minLevel":2,"maxLevel":4}]'::jsonb
WHERE "id" = 'route-29' AND "id" IS NOT DISTINCT FROM 'route-29' AND "region_id" IS NOT DISTINCT FROM 'johto' AND "order" IS NOT DISTINCT FROM 0 AND "name" IS NOT DISTINCT FROM 'Route 29' AND "description" IS NOT DISTINCT FROM 'Le chemin herbeux qui relie Bourg Geon à Ville Griotte.' AND "image" IS NOT DISTINCT FROM NULL AND "habitat" IS NOT DISTINCT FROM 'grassland' AND "min_power" IS NOT DISTINCT FROM 0 AND "enabled" IS NOT DISTINCT FROM true AND "required_types" IS NOT DISTINCT FROM '[]'::jsonb AND "affinity_types" IS NOT DISTINCT FROM '["normal","flying"]'::jsonb AND "durations_minutes" IS NOT DISTINCT FROM '[2,5,15,60,240,480]'::jsonb AND "encounters" IS NOT DISTINCT FROM '[{"speciesId":161,"weight":30,"minLevel":3,"maxLevel":6},{"speciesId":163,"weight":25,"minLevel":3,"maxLevel":6},{"speciesId":165,"weight":15,"minLevel":4,"maxLevel":6},{"speciesId":187,"weight":15,"minLevel":4,"maxLevel":6},{"speciesId":167,"weight":15,"minLevel":4,"maxLevel":6}]'::jsonb AND "loot_table_id" IS NOT DISTINCT FROM 'butin-route' AND "unlock" IS NOT DISTINCT FROM '{"type":"always"}'::jsonb;--> statement-breakpoint
INSERT INTO "zones" ("content_version_id", "id", "region_id", "order", "name", "description", "image", "habitat", "min_power", "enabled", "required_types", "affinity_types", "durations_minutes", "encounters", "loot_table_id", "unlock")
SELECT v."id", 'routes-30-31', 'johto', 1, 'Routes 30 et 31', 'Les sentiers boisés au nord de Ville Griotte, où Coxy et Mimigal se relaient jour et nuit.', NULL, 'forest', 100, true, '[]'::jsonb, '["bug","grass"]'::jsonb, '[2,5,15,60,240,480]'::jsonb, '[{"speciesId":165,"weight":25,"minLevel":3,"maxLevel":6},{"speciesId":167,"weight":25,"minLevel":3,"maxLevel":6},{"speciesId":163,"weight":12,"minLevel":3,"maxLevel":6},{"speciesId":161,"weight":10,"minLevel":4,"maxLevel":6},{"speciesId":10,"weight":8,"minLevel":3,"maxLevel":5},{"speciesId":13,"weight":8,"minLevel":3,"maxLevel":5},{"speciesId":69,"weight":12,"minLevel":4,"maxLevel":6}]'::jsonb, 'butin-foret', '{"type":"regionDexPercent","regionId":"johto","percent":3}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
UPDATE "zones" SET "order" = 2, "min_power" = 180, "affinity_types" = '["ghost","grass","normal"]'::jsonb, "encounters" = '[{"speciesId":163,"weight":25,"minLevel":4,"maxLevel":7},{"speciesId":198,"weight":8,"minLevel":5,"maxLevel":8},{"speciesId":177,"weight":12,"minLevel":5,"maxLevel":8},{"speciesId":19,"weight":25,"minLevel":4,"maxLevel":7},{"speciesId":92,"weight":20,"minLevel":4,"maxLevel":7},{"speciesId":69,"weight":10,"minLevel":4,"maxLevel":7}]'::jsonb, "unlock" = '{"type":"trainerDefeated","trainerId":"scout-willy"}'::jsonb
WHERE "id" = 'tour-chetiflor' AND "id" IS NOT DISTINCT FROM 'tour-chetiflor' AND "region_id" IS NOT DISTINCT FROM 'johto' AND "order" IS NOT DISTINCT FROM 1 AND "name" IS NOT DISTINCT FROM 'Tour Chétiflor' AND "description" IS NOT DISTINCT FROM 'Une vieille tour de bois qui oscille doucement. Des ombres y rôdent la nuit.' AND "image" IS NOT DISTINCT FROM NULL AND "habitat" IS NOT DISTINCT FROM 'urban' AND "min_power" IS NOT DISTINCT FROM 200 AND "enabled" IS NOT DISTINCT FROM true AND "required_types" IS NOT DISTINCT FROM '[]'::jsonb AND "affinity_types" IS NOT DISTINCT FROM '["ghost","psychic","dark"]'::jsonb AND "durations_minutes" IS NOT DISTINCT FROM '[2,5,15,60,240,480]'::jsonb AND "encounters" IS NOT DISTINCT FROM '[{"speciesId":177,"weight":25,"minLevel":10,"maxLevel":14},{"speciesId":198,"weight":20,"minLevel":10,"maxLevel":14},{"speciesId":200,"weight":15,"minLevel":12,"maxLevel":15},{"speciesId":167,"weight":25,"minLevel":9,"maxLevel":12},{"speciesId":203,"weight":15,"minLevel":12,"maxLevel":15}]'::jsonb AND "loot_table_id" IS NOT DISTINCT FROM 'butin-grotte' AND "unlock" IS NOT DISTINCT FROM '{"type":"regionDexPercent","regionId":"johto","percent":5}'::jsonb;--> statement-breakpoint
INSERT INTO "zones" ("content_version_id", "id", "region_id", "order", "name", "description", "image", "habitat", "min_power", "enabled", "required_types", "affinity_types", "durations_minutes", "encounters", "loot_table_id", "unlock")
SELECT v."id", 'route-32', 'johto', 3, 'Route 32', 'La longue route qui descend de Mauville vers les Caves Jumelles, bordée d’étangs.', NULL, 'grassland', 250, true, '[]'::jsonb, '["electric","grass","water"]'::jsonb, '[2,5,15,60,240,480]'::jsonb, '[{"speciesId":179,"weight":25,"minLevel":6,"maxLevel":9},{"speciesId":187,"weight":18,"minLevel":6,"maxLevel":9},{"speciesId":163,"weight":12,"minLevel":6,"maxLevel":9},{"speciesId":211,"weight":6,"minLevel":7,"maxLevel":10},{"speciesId":23,"weight":10,"minLevel":6,"maxLevel":9},{"speciesId":69,"weight":10,"minLevel":6,"maxLevel":9},{"speciesId":72,"weight":9,"minLevel":6,"maxLevel":9},{"speciesId":129,"weight":10,"minLevel":5,"maxLevel":10}]'::jsonb, 'butin-route', '{"type":"badgeCount","count":1,"regionId":"johto"}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
INSERT INTO "zones" ("content_version_id", "id", "region_id", "order", "name", "description", "image", "habitat", "min_power", "enabled", "required_types", "affinity_types", "durations_minutes", "encounters", "loot_table_id", "unlock")
SELECT v."id", 'caves-jumelles', 'johto', 4, 'Caves Jumelles', 'Un réseau de galeries humides sous la Route 32, où barbotent les Axoloto.', NULL, 'cave', 300, true, '[]'::jsonb, '["rock","ground","water"]'::jsonb, '[2,5,15,60,240,480]'::jsonb, '[{"speciesId":194,"weight":25,"minLevel":7,"maxLevel":10},{"speciesId":41,"weight":22,"minLevel":6,"maxLevel":10},{"speciesId":74,"weight":22,"minLevel":6,"maxLevel":10},{"speciesId":27,"weight":10,"minLevel":7,"maxLevel":10},{"speciesId":19,"weight":12,"minLevel":6,"maxLevel":9},{"speciesId":95,"weight":6,"minLevel":8,"maxLevel":11},{"speciesId":195,"weight":3,"minLevel":15,"maxLevel":18}]'::jsonb, 'butin-grotte', '{"type":"badgeCount","count":1,"regionId":"johto"}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
INSERT INTO "zones" ("content_version_id", "id", "region_id", "order", "name", "description", "image", "habitat", "min_power", "enabled", "required_types", "affinity_types", "durations_minutes", "encounters", "loot_table_id", "unlock")
SELECT v."id", 'ruines-alpha', 'johto', 5, 'Ruines d’Alpha', 'Des ruines millénaires couvertes d’inscriptions. Les Zarbi semblent former des lettres.', NULL, 'rough-terrain', 380, true, '[]'::jsonb, '["psychic","rock"]'::jsonb, '[2,5,15,60,240,480]'::jsonb, '[{"speciesId":201,"weight":32,"minLevel":8,"maxLevel":12},{"speciesId":177,"weight":22,"minLevel":8,"maxLevel":12},{"speciesId":194,"weight":14,"minLevel":8,"maxLevel":12},{"speciesId":235,"weight":8,"minLevel":9,"maxLevel":13},{"speciesId":63,"weight":12,"minLevel":8,"maxLevel":12},{"speciesId":54,"weight":12,"minLevel":8,"maxLevel":12}]'::jsonb, 'butin-fouilles', '{"type":"trainerDefeated","trainerId":"montagnard-anthony"}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
INSERT INTO "zones" ("content_version_id", "id", "region_id", "order", "name", "description", "image", "habitat", "min_power", "enabled", "required_types", "affinity_types", "durations_minutes", "encounters", "loot_table_id", "unlock")
SELECT v."id", 'puits-ramoloss', 'johto', 6, 'Puits Ramoloss', 'Le puits d’Écorcia, où la Team Rocket coupe la queue des Ramoloss pour la revendre.', NULL, 'cave', 420, true, '[]'::jsonb, '["water","psychic"]'::jsonb, '[2,5,15,60,240,480]'::jsonb, '[{"speciesId":79,"weight":40,"minLevel":9,"maxLevel":13},{"speciesId":41,"weight":25,"minLevel":9,"maxLevel":13},{"speciesId":194,"weight":15,"minLevel":9,"maxLevel":13},{"speciesId":118,"weight":10,"minLevel":9,"maxLevel":13},{"speciesId":129,"weight":10,"minLevel":8,"maxLevel":12}]'::jsonb, 'butin-grotte', '{"type":"trainerDefeated","trainerId":"montagnard-anthony"}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
INSERT INTO "zones" ("content_version_id", "id", "region_id", "order", "name", "description", "image", "habitat", "min_power", "enabled", "required_types", "affinity_types", "durations_minutes", "encounters", "loot_table_id", "unlock")
SELECT v."id", 'bois-aux-chenes', 'johto', 7, 'Bois aux Chênes', 'Une forêt si dense que le soleil n’y perce jamais. Un petit autel y est dédié au protecteur des bois.', NULL, 'forest', 480, true, '[]'::jsonb, '["bug","grass"]'::jsonb, '[2,5,15,60,240,480]'::jsonb, '[{"speciesId":204,"weight":18,"minLevel":10,"maxLevel":14},{"speciesId":165,"weight":12,"minLevel":10,"maxLevel":14},{"speciesId":167,"weight":12,"minLevel":10,"maxLevel":14},{"speciesId":163,"weight":10,"minLevel":10,"maxLevel":14},{"speciesId":46,"weight":16,"minLevel":10,"maxLevel":14},{"speciesId":43,"weight":14,"minLevel":10,"maxLevel":14},{"speciesId":54,"weight":10,"minLevel":10,"maxLevel":14},{"speciesId":166,"weight":4,"minLevel":16,"maxLevel":18},{"speciesId":168,"weight":4,"minLevel":20,"maxLevel":22}]'::jsonb, 'butin-foret', '{"type":"badgeCount","count":2,"regionId":"johto"}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
INSERT INTO "zones" ("content_version_id", "id", "region_id", "order", "name", "description", "image", "habitat", "min_power", "enabled", "required_types", "affinity_types", "durations_minutes", "encounters", "loot_table_id", "unlock")
SELECT v."id", 'routes-34-35', 'johto', 8, 'Routes 34 et 35', 'Les prés qui entourent Doublonville et sa Pension. Un Métamorph s’y cache parfois.', NULL, 'grassland', 520, true, '[]'::jsonb, '["normal","fairy","grass"]'::jsonb, '[2,5,15,60,240,480]'::jsonb, '[{"speciesId":209,"weight":18,"minLevel":12,"maxLevel":16},{"speciesId":191,"weight":15,"minLevel":12,"maxLevel":16},{"speciesId":193,"weight":8,"minLevel":12,"maxLevel":16},{"speciesId":161,"weight":8,"minLevel":12,"maxLevel":16},{"speciesId":96,"weight":12,"minLevel":12,"maxLevel":16},{"speciesId":39,"weight":10,"minLevel":12,"maxLevel":16},{"speciesId":63,"weight":7,"minLevel":12,"maxLevel":16},{"speciesId":132,"weight":6,"minLevel":12,"maxLevel":16},{"speciesId":29,"weight":6,"minLevel":12,"maxLevel":16},{"speciesId":32,"weight":6,"minLevel":12,"maxLevel":16},{"speciesId":162,"weight":4,"minLevel":16,"maxLevel":18}]'::jsonb, 'butin-route', '{"type":"badgeCount","count":2,"regionId":"johto"}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
INSERT INTO "zones" ("content_version_id", "id", "region_id", "order", "name", "description", "image", "habitat", "min_power", "enabled", "required_types", "affinity_types", "durations_minutes", "encounters", "loot_table_id", "unlock")
SELECT v."id", 'antre-noir', 'johto', 9, 'Antre Noir', 'Une grotte plongée dans le noir complet. On y bute sur des Insolourdo et des Qulbutoké.', NULL, 'cave', 560, true, '[]'::jsonb, '["normal","psychic","rock"]'::jsonb, '[2,5,15,60,240,480]'::jsonb, '[{"speciesId":216,"weight":14,"minLevel":13,"maxLevel":17},{"speciesId":206,"weight":10,"minLevel":13,"maxLevel":17},{"speciesId":202,"weight":7,"minLevel":14,"maxLevel":18},{"speciesId":41,"weight":26,"minLevel":12,"maxLevel":16},{"speciesId":74,"weight":25,"minLevel":12,"maxLevel":16},{"speciesId":95,"weight":8,"minLevel":14,"maxLevel":18},{"speciesId":42,"weight":5,"minLevel":22,"maxLevel":25}]'::jsonb, 'butin-grotte', '{"type":"badgeCount","count":2,"regionId":"johto"}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
INSERT INTO "zones" ("content_version_id", "id", "region_id", "order", "name", "description", "image", "habitat", "min_power", "enabled", "required_types", "affinity_types", "durations_minutes", "encounters", "loot_table_id", "unlock")
SELECT v."id", 'routes-36-37', 'johto', 10, 'Routes 36 et 37', 'Les routes qui mènent à Rosalia, où paissent les Cerfrousse à la nuit tombée.', NULL, 'grassland', 800, true, '[]'::jsonb, '["normal","psychic","dark"]'::jsonb, '[2,5,15,60,240,480]'::jsonb, '[{"speciesId":234,"weight":14,"minLevel":16,"maxLevel":20},{"speciesId":198,"weight":10,"minLevel":16,"maxLevel":20},{"speciesId":177,"weight":10,"minLevel":16,"maxLevel":20},{"speciesId":163,"weight":10,"minLevel":16,"maxLevel":20},{"speciesId":164,"weight":5,"minLevel":20,"maxLevel":22},{"speciesId":166,"weight":6,"minLevel":18,"maxLevel":20},{"speciesId":168,"weight":6,"minLevel":22,"maxLevel":24},{"speciesId":58,"weight":10,"minLevel":16,"maxLevel":20},{"speciesId":37,"weight":10,"minLevel":16,"maxLevel":20},{"speciesId":17,"weight":9,"minLevel":18,"maxLevel":21},{"speciesId":69,"weight":10,"minLevel":16,"maxLevel":20}]'::jsonb, 'butin-route', '{"type":"badgeCount","count":3,"regionId":"johto"}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
INSERT INTO "zones" ("content_version_id", "id", "region_id", "order", "name", "description", "image", "habitat", "min_power", "enabled", "required_types", "affinity_types", "durations_minutes", "encounters", "loot_table_id", "unlock")
SELECT v."id", 'tour-cendree', 'johto', 11, 'Tour Cendrée', 'Les ruines calcinées d’une tour de Rosalia. Trois Pokémon légendaires y seraient nés des flammes.', NULL, 'urban', 850, true, '[]'::jsonb, '["fire","dark","poison"]'::jsonb, '[2,5,15,60,240,480]'::jsonb, '[{"speciesId":218,"weight":18,"minLevel":16,"maxLevel":21},{"speciesId":228,"weight":12,"minLevel":16,"maxLevel":21},{"speciesId":19,"weight":22,"minLevel":16,"maxLevel":21},{"speciesId":109,"weight":18,"minLevel":16,"maxLevel":21},{"speciesId":20,"weight":10,"minLevel":20,"maxLevel":23},{"speciesId":58,"weight":10,"minLevel":16,"maxLevel":21},{"speciesId":41,"weight":10,"minLevel":16,"maxLevel":21}]'::jsonb, 'butin-grotte', '{"type":"badgeCount","count":3,"regionId":"johto"}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
INSERT INTO "zones" ("content_version_id", "id", "region_id", "order", "name", "description", "image", "habitat", "min_power", "enabled", "required_types", "affinity_types", "durations_minutes", "encounters", "loot_table_id", "unlock")
SELECT v."id", 'routes-38-39', 'johto', 12, 'Routes 38 et 39', 'Les pâturages de la Ferme Meuh Meuh, entre Rosalia et Oliville.', NULL, 'grassland', 900, true, '[]'::jsonb, '["normal","electric","water"]'::jsonb, '[2,5,15,60,240,480]'::jsonb, '[{"speciesId":241,"weight":12,"minLevel":18,"maxLevel":22},{"speciesId":209,"weight":8,"minLevel":18,"maxLevel":22},{"speciesId":164,"weight":8,"minLevel":20,"maxLevel":24},{"speciesId":52,"weight":15,"minLevel":18,"maxLevel":22},{"speciesId":20,"weight":10,"minLevel":18,"maxLevel":22},{"speciesId":17,"weight":10,"minLevel":18,"maxLevel":22},{"speciesId":79,"weight":10,"minLevel":18,"maxLevel":22},{"speciesId":81,"weight":10,"minLevel":18,"maxLevel":22},{"speciesId":22,"weight":6,"minLevel":20,"maxLevel":24},{"speciesId":210,"weight":3,"minLevel":23,"maxLevel":25}]'::jsonb, 'butin-route', '{"type":"badgeCount","count":3,"regionId":"johto"}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
INSERT INTO "zones" ("content_version_id", "id", "region_id", "order", "name", "description", "image", "habitat", "min_power", "enabled", "required_types", "affinity_types", "durations_minutes", "encounters", "loot_table_id", "unlock")
SELECT v."id", 'routes-42-44', 'johto', 13, 'Routes 42 à 44', 'Les routes de montagne qui relient Rosalia, Acajou et Ebenelle, au pied du Mont Creuset.', NULL, 'mountain', 1300, true, '[]'::jsonb, '["normal","electric","water"]'::jsonb, '[60,240,480]'::jsonb, '[{"speciesId":190,"weight":12,"minLevel":22,"maxLevel":28},{"speciesId":203,"weight":10,"minLevel":22,"maxLevel":28},{"speciesId":179,"weight":10,"minLevel":22,"maxLevel":26},{"speciesId":180,"weight":6,"minLevel":24,"maxLevel":28},{"speciesId":183,"weight":10,"minLevel":22,"maxLevel":28},{"speciesId":223,"weight":10,"minLevel":22,"maxLevel":28},{"speciesId":21,"weight":10,"minLevel":22,"maxLevel":28},{"speciesId":22,"weight":6,"minLevel":26,"maxLevel":30},{"speciesId":56,"weight":8,"minLevel":22,"maxLevel":28},{"speciesId":77,"weight":8,"minLevel":22,"maxLevel":28},{"speciesId":224,"weight":3,"minLevel":25,"maxLevel":30}]'::jsonb, 'butin-route', '{"type":"badgeCount","count":4,"regionId":"johto"}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
INSERT INTO "zones" ("content_version_id", "id", "region_id", "order", "name", "description", "image", "habitat", "min_power", "enabled", "required_types", "affinity_types", "durations_minutes", "encounters", "loot_table_id", "unlock")
SELECT v."id", 'mont-creuset', 'johto', 14, 'Mont Creuset', 'Une montagne creusée de cascades et de galeries. Un Maître Karaté s’y entraîne.', NULL, 'cave', 1400, true, '[]'::jsonb, '["fighting","rock","water"]'::jsonb, '[60,240,480]'::jsonb, '[{"speciesId":183,"weight":16,"minLevel":22,"maxLevel":28},{"speciesId":184,"weight":4,"minLevel":26,"maxLevel":30},{"speciesId":66,"weight":16,"minLevel":22,"maxLevel":28},{"speciesId":74,"weight":15,"minLevel":22,"maxLevel":28},{"speciesId":75,"weight":8,"minLevel":25,"maxLevel":30},{"speciesId":41,"weight":12,"minLevel":22,"maxLevel":28},{"speciesId":42,"weight":8,"minLevel":25,"maxLevel":30},{"speciesId":217,"weight":3,"minLevel":30,"maxLevel":32}]'::jsonb, 'butin-grotte', '{"type":"badgeCount","count":4,"regionId":"johto"}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
INSERT INTO "zones" ("content_version_id", "id", "region_id", "order", "name", "description", "image", "habitat", "min_power", "enabled", "required_types", "affinity_types", "durations_minutes", "encounters", "loot_table_id", "unlock")
SELECT v."id", 'routes-40-41', 'johto', 15, 'Routes 40 et 41', 'Le bras de mer entre Oliville et Irisia, semé d’îlots. Il faut un Pokémon Eau pour le traverser.', NULL, 'sea', 1500, true, '[{"type":"water","count":1}]'::jsonb, '["water"]'::jsonb, '[60,240,480]'::jsonb, '[{"speciesId":170,"weight":16,"minLevel":22,"maxLevel":28},{"speciesId":226,"weight":5,"minLevel":24,"maxLevel":30},{"speciesId":213,"weight":6,"minLevel":22,"maxLevel":28},{"speciesId":171,"weight":3,"minLevel":27,"maxLevel":30},{"speciesId":72,"weight":24,"minLevel":22,"maxLevel":28},{"speciesId":98,"weight":10,"minLevel":22,"maxLevel":28},{"speciesId":116,"weight":8,"minLevel":22,"maxLevel":28},{"speciesId":120,"weight":8,"minLevel":22,"maxLevel":28},{"speciesId":90,"weight":6,"minLevel":22,"maxLevel":28},{"speciesId":73,"weight":6,"minLevel":28,"maxLevel":32},{"speciesId":129,"weight":8,"minLevel":20,"maxLevel":30}]'::jsonb, 'butin-mer', '{"type":"badgeCount","count":4,"regionId":"johto"}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
INSERT INTO "zones" ("content_version_id", "id", "region_id", "order", "name", "description", "image", "habitat", "min_power", "enabled", "required_types", "affinity_types", "durations_minutes", "encounters", "loot_table_id", "unlock")
SELECT v."id", 'phare-oliville', 'johto', 16, 'Phare d’Oliville', 'Le grand phare du port, dont la lumière vient d’un Pharamp malade. Des Magnéti y grésillent.', NULL, 'urban', 2000, true, '[]'::jsonb, '["electric","steel","water"]'::jsonb, '[60,240,480]'::jsonb, '[{"speciesId":180,"weight":16,"minLevel":28,"maxLevel":34},{"speciesId":181,"weight":4,"minLevel":32,"maxLevel":36},{"speciesId":81,"weight":22,"minLevel":28,"maxLevel":34},{"speciesId":82,"weight":8,"minLevel":32,"maxLevel":36},{"speciesId":52,"weight":14,"minLevel":28,"maxLevel":34},{"speciesId":72,"weight":14,"minLevel":28,"maxLevel":34},{"speciesId":171,"weight":10,"minLevel":28,"maxLevel":34},{"speciesId":53,"weight":6,"minLevel":30,"maxLevel":36},{"speciesId":79,"weight":6,"minLevel":28,"maxLevel":34}]'::jsonb, 'butin-mer', '{"type":"badgeCount","count":5,"regionId":"johto"}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
UPDATE "zones" SET "order" = 17, "description" = 'Un grand lac agité au nord d’Acajou. On murmure qu’un Léviator rouge y aurait été aperçu.', "min_power" = 2400, "affinity_types" = '["water","bug"]'::jsonb, "durations_minutes" = '[60,240,480]'::jsonb, "encounters" = '[{"speciesId":129,"weight":32,"minLevel":28,"maxLevel":38},{"speciesId":194,"weight":14,"minLevel":30,"maxLevel":36},{"speciesId":195,"weight":8,"minLevel":32,"maxLevel":38},{"speciesId":193,"weight":8,"minLevel":30,"maxLevel":36},{"speciesId":118,"weight":12,"minLevel":30,"maxLevel":36},{"speciesId":119,"weight":4,"minLevel":34,"maxLevel":40},{"speciesId":60,"weight":10,"minLevel":30,"maxLevel":36},{"speciesId":61,"weight":6,"minLevel":32,"maxLevel":38},{"speciesId":130,"weight":3,"minLevel":36,"maxLevel":40}]'::jsonb, "unlock" = '{"type":"badgeCount","count":6,"regionId":"johto"}'::jsonb
WHERE "id" = 'lac-colere' AND "id" IS NOT DISTINCT FROM 'lac-colere' AND "region_id" IS NOT DISTINCT FROM 'johto' AND "order" IS NOT DISTINCT FROM 2 AND "name" IS NOT DISTINCT FROM 'Lac Colère' AND "description" IS NOT DISTINCT FROM 'Un grand lac agité. On murmure qu’un Léviator rouge y aurait été aperçu.' AND "image" IS NOT DISTINCT FROM NULL AND "habitat" IS NOT DISTINCT FROM 'waters-edge' AND "min_power" IS NOT DISTINCT FROM 400 AND "enabled" IS NOT DISTINCT FROM true AND "required_types" IS NOT DISTINCT FROM '[{"type":"water","count":1}]'::jsonb AND "affinity_types" IS NOT DISTINCT FROM '["water"]'::jsonb AND "durations_minutes" IS NOT DISTINCT FROM '[2,5,15,60,240,480]'::jsonb AND "encounters" IS NOT DISTINCT FROM '[{"speciesId":183,"weight":25,"minLevel":15,"maxLevel":20},{"speciesId":194,"weight":20,"minLevel":15,"maxLevel":20},{"speciesId":194,"formId":10253,"weight":5,"minLevel":15,"maxLevel":20},{"speciesId":170,"weight":15,"minLevel":18,"maxLevel":22},{"speciesId":223,"weight":15,"minLevel":18,"maxLevel":22},{"speciesId":211,"weight":10,"minLevel":20,"maxLevel":24}]'::jsonb AND "loot_table_id" IS NOT DISTINCT FROM 'butin-mer' AND "unlock" IS NOT DISTINCT FROM '{"type":"trainerDefeated","trainerId":"albert"}'::jsonb;--> statement-breakpoint
INSERT INTO "zones" ("content_version_id", "id", "region_id", "order", "name", "description", "image", "habitat", "min_power", "enabled", "required_types", "affinity_types", "durations_minutes", "encounters", "loot_table_id", "unlock")
SELECT v."id", 'route-de-glace', 'johto', 18, 'Route de Glace', 'Un passage gelé entre Acajou et Ebenelle, où l’on glisse d’un bout à l’autre de la grotte.', NULL, 'cave', 2800, true, '[]'::jsonb, '["ice","water","dark"]'::jsonb, '[60,240,480]'::jsonb, '[{"speciesId":220,"weight":24,"minLevel":32,"maxLevel":38},{"speciesId":221,"weight":4,"minLevel":36,"maxLevel":40},{"speciesId":225,"weight":7,"minLevel":32,"maxLevel":38},{"speciesId":215,"weight":7,"minLevel":32,"maxLevel":38},{"speciesId":86,"weight":16,"minLevel":32,"maxLevel":38},{"speciesId":87,"weight":4,"minLevel":36,"maxLevel":40},{"speciesId":41,"weight":12,"minLevel":32,"maxLevel":38},{"speciesId":42,"weight":10,"minLevel":34,"maxLevel":40},{"speciesId":74,"weight":10,"minLevel":32,"maxLevel":38}]'::jsonb, 'butin-grotte', '{"type":"badgeCount","count":7,"regionId":"johto"}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
INSERT INTO "zones" ("content_version_id", "id", "region_id", "order", "name", "description", "image", "habitat", "min_power", "enabled", "required_types", "affinity_types", "durations_minutes", "encounters", "loot_table_id", "unlock")
SELECT v."id", 'routes-45-46', 'johto', 19, 'Routes 45 et 46', 'Un sentier de montagne abrupt au sud d’Ebenelle, où dévalent les Phanpy.', NULL, 'mountain', 3200, true, '[]'::jsonb, '["ground","rock","normal"]'::jsonb, '[60,240,480]'::jsonb, '[{"speciesId":231,"weight":18,"minLevel":36,"maxLevel":42},{"speciesId":232,"weight":4,"minLevel":40,"maxLevel":44},{"speciesId":216,"weight":10,"minLevel":36,"maxLevel":42},{"speciesId":217,"weight":5,"minLevel":40,"maxLevel":44},{"speciesId":74,"weight":12,"minLevel":36,"maxLevel":42},{"speciesId":75,"weight":10,"minLevel":38,"maxLevel":44},{"speciesId":57,"weight":10,"minLevel":38,"maxLevel":44},{"speciesId":66,"weight":10,"minLevel":36,"maxLevel":42},{"speciesId":67,"weight":6,"minLevel":40,"maxLevel":44},{"speciesId":22,"weight":8,"minLevel":38,"maxLevel":44}]'::jsonb, 'butin-fouilles', '{"type":"badgeCount","count":8,"regionId":"johto"}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
INSERT INTO "zones" ("content_version_id", "id", "region_id", "order", "name", "description", "image", "habitat", "min_power", "enabled", "required_types", "affinity_types", "durations_minutes", "encounters", "loot_table_id", "unlock")
SELECT v."id", 'routes-26-27', 'johto', 20, 'Routes 26 et 27', 'Les routes côtières qui mènent au Plateau Indigo. Les dresseurs y sont tous aguerris.', NULL, 'waters-edge', 3600, true, '[]'::jsonb, '["normal","water","psychic"]'::jsonb, '[60,240,480]'::jsonb, '[{"speciesId":164,"weight":10,"minLevel":40,"maxLevel":46},{"speciesId":178,"weight":8,"minLevel":40,"maxLevel":46},{"speciesId":195,"weight":8,"minLevel":40,"maxLevel":46},{"speciesId":232,"weight":6,"minLevel":42,"maxLevel":46},{"speciesId":229,"weight":5,"minLevel":42,"maxLevel":46},{"speciesId":20,"weight":10,"minLevel":40,"maxLevel":46},{"speciesId":22,"weight":10,"minLevel":40,"maxLevel":46},{"speciesId":78,"weight":8,"minLevel":42,"maxLevel":46},{"speciesId":85,"weight":8,"minLevel":42,"maxLevel":46},{"speciesId":57,"weight":8,"minLevel":42,"maxLevel":46},{"speciesId":73,"weight":8,"minLevel":40,"maxLevel":46}]'::jsonb, 'butin-elite', '{"type":"badgeCount","count":8,"regionId":"johto"}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
INSERT INTO "zones" ("content_version_id", "id", "region_id", "order", "name", "description", "image", "habitat", "min_power", "enabled", "required_types", "affinity_types", "durations_minutes", "encounters", "loot_table_id", "unlock")
SELECT v."id", 'labo-orme', 'johto', 21, 'Labo du Prof. Orme', 'Le Prof. Orme élève des Germignon, Héricendre et Kaiminus, et étudie un mystérieux œuf de Togepi. Il ouvre son labo aux dresseurs confirmés.', NULL, 'grassland', 1000, true, '[]'::jsonb, '["grass","fire","water"]'::jsonb, '[240,480]'::jsonb, '[{"speciesId":161,"weight":22,"minLevel":14,"maxLevel":18},{"speciesId":163,"weight":22,"minLevel":14,"maxLevel":18},{"speciesId":165,"weight":14,"minLevel":14,"maxLevel":18},{"speciesId":167,"weight":14,"minLevel":14,"maxLevel":18},{"speciesId":187,"weight":14,"minLevel":14,"maxLevel":18},{"speciesId":152,"weight":3,"minLevel":10,"maxLevel":12},{"speciesId":155,"weight":3,"minLevel":10,"maxLevel":12},{"speciesId":158,"weight":3,"minLevel":10,"maxLevel":12},{"speciesId":175,"weight":3,"minLevel":5,"maxLevel":8}]'::jsonb, 'butin-foret', '{"type":"allOf","conditions":[{"type":"badgeCount","count":2,"regionId":"johto"},{"type":"regionDexPercent","regionId":"johto","percent":20}]}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
INSERT INTO "zones" ("content_version_id", "id", "region_id", "order", "name", "description", "image", "habitat", "min_power", "enabled", "required_types", "affinity_types", "durations_minutes", "encounters", "loot_table_id", "unlock")
SELECT v."id", 'arbre-etrange', 'johto', 22, 'Arbre étrange', 'Un arbre bloque la Route 36… et il bouge quand on l’arrose. Il faut un Pokémon Eau pour le déloger.', NULL, 'forest', 1400, true, '[{"type":"water","count":1}]'::jsonb, '["grass","rock","water"]'::jsonb, '[240,480]'::jsonb, '[{"speciesId":191,"weight":16,"minLevel":18,"maxLevel":22},{"speciesId":192,"weight":4,"minLevel":22,"maxLevel":26},{"speciesId":187,"weight":16,"minLevel":18,"maxLevel":22},{"speciesId":188,"weight":8,"minLevel":20,"maxLevel":24},{"speciesId":43,"weight":14,"minLevel":18,"maxLevel":22},{"speciesId":69,"weight":14,"minLevel":18,"maxLevel":22},{"speciesId":190,"weight":8,"minLevel":18,"maxLevel":22},{"speciesId":185,"weight":4,"minLevel":20,"maxLevel":22}]'::jsonb, 'butin-foret', '{"type":"allOf","conditions":[{"type":"badgeCount","count":3,"regionId":"johto"},{"type":"regionDexPercent","regionId":"johto","percent":30}]}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
INSERT INTO "zones" ("content_version_id", "id", "region_id", "order", "name", "description", "image", "habitat", "min_power", "enabled", "required_types", "affinity_types", "durations_minutes", "encounters", "loot_table_id", "unlock")
SELECT v."id", 'parc-naturel', 'johto', 23, 'Parc Naturel', 'Le parc de Doublonville et son Concours de Capture d’insectes. Seules les équipes d’au moins deux Pokémon Insecte y participent ; un Scarhino s’y montre parfois.', NULL, 'grassland', 1800, true, '[{"type":"bug","count":2}]'::jsonb, '["bug","grass"]'::jsonb, '[240,480]'::jsonb, '[{"speciesId":165,"weight":12,"minLevel":20,"maxLevel":26},{"speciesId":166,"weight":6,"minLevel":24,"maxLevel":28},{"speciesId":167,"weight":12,"minLevel":20,"maxLevel":26},{"speciesId":168,"weight":6,"minLevel":24,"maxLevel":28},{"speciesId":193,"weight":8,"minLevel":20,"maxLevel":26},{"speciesId":204,"weight":10,"minLevel":20,"maxLevel":26},{"speciesId":191,"weight":8,"minLevel":20,"maxLevel":26},{"speciesId":12,"weight":6,"minLevel":24,"maxLevel":28},{"speciesId":15,"weight":6,"minLevel":24,"maxLevel":28},{"speciesId":48,"weight":10,"minLevel":20,"maxLevel":26},{"speciesId":46,"weight":10,"minLevel":20,"maxLevel":26},{"speciesId":214,"weight":3,"minLevel":24,"maxLevel":28}]'::jsonb, 'butin-foret', '{"type":"allOf","conditions":[{"type":"badgeCount","count":3,"regionId":"johto"},{"type":"trainerDefeated","trainerId":"scout-hugo"}]}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
INSERT INTO "zones" ("content_version_id", "id", "region_id", "order", "name", "description", "image", "habitat", "min_power", "enabled", "required_types", "affinity_types", "durations_minutes", "encounters", "loot_table_id", "unlock")
SELECT v."id", 'parc-safari-johto', 'johto', 24, 'Parc Safari de Johto', 'La réserve ouverte au-delà d’Irisia, sur des terres arides et rocheuses. Scorplane et Airmure ne se montrent qu’aux dresseurs patients.', NULL, 'rough-terrain', 2600, true, '[]'::jsonb, '["ground","rock","flying"]'::jsonb, '[240,480]'::jsonb, '[{"speciesId":231,"weight":14,"minLevel":28,"maxLevel":34},{"speciesId":195,"weight":10,"minLevel":28,"maxLevel":34},{"speciesId":178,"weight":8,"minLevel":30,"maxLevel":34},{"speciesId":203,"weight":8,"minLevel":28,"maxLevel":34},{"speciesId":111,"weight":14,"minLevel":28,"maxLevel":34},{"speciesId":102,"weight":12,"minLevel":28,"maxLevel":34},{"speciesId":114,"weight":10,"minLevel":28,"maxLevel":34},{"speciesId":84,"weight":10,"minLevel":28,"maxLevel":34},{"speciesId":27,"weight":8,"minLevel":28,"maxLevel":34},{"speciesId":207,"weight":4,"minLevel":28,"maxLevel":34},{"speciesId":227,"weight":2,"minLevel":30,"maxLevel":34}]'::jsonb, 'butin-fouilles', '{"type":"allOf","conditions":[{"type":"badgeCount","count":5,"regionId":"johto"},{"type":"regionDexPercent","regionId":"johto","percent":40}]}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
INSERT INTO "zones" ("content_version_id", "id", "region_id", "order", "name", "description", "image", "habitat", "min_power", "enabled", "required_types", "affinity_types", "durations_minutes", "encounters", "loot_table_id", "unlock")
SELECT v."id", 'mont-argente', 'johto', 25, 'Mont Argenté', 'La montagne interdite entre Johto et Kanto, réservée aux Maîtres. Un dresseur silencieux attendrait au sommet.', NULL, 'mountain', 5000, true, '[]'::jsonb, '["rock","ghost","ground"]'::jsonb, '[240,480]'::jsonb, '[{"speciesId":217,"weight":12,"minLevel":45,"maxLevel":52},{"speciesId":232,"weight":10,"minLevel":45,"maxLevel":52},{"speciesId":229,"weight":8,"minLevel":45,"maxLevel":52},{"speciesId":75,"weight":12,"minLevel":45,"maxLevel":52},{"speciesId":95,"weight":10,"minLevel":45,"maxLevel":52},{"speciesId":57,"weight":10,"minLevel":45,"maxLevel":52},{"speciesId":105,"weight":8,"minLevel":45,"maxLevel":52},{"speciesId":59,"weight":6,"minLevel":48,"maxLevel":52},{"speciesId":78,"weight":6,"minLevel":48,"maxLevel":52},{"speciesId":200,"weight":3,"minLevel":45,"maxLevel":50},{"speciesId":246,"weight":3,"minLevel":20,"maxLevel":25}]'::jsonb, 'butin-elite', '{"type":"allOf","conditions":[{"type":"trainerDefeated","trainerId":"maitre-peter"},{"type":"regionDexPercent","regionId":"johto","percent":60}]}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
INSERT INTO "zones" ("content_version_id", "id", "region_id", "order", "name", "description", "image", "habitat", "min_power", "enabled", "required_types", "affinity_types", "durations_minutes", "encounters", "loot_table_id", "unlock")
SELECT v."id", 'tourb-iles', 'johto', 26, 'Tourb’Îles', 'Quatre îles cernées de tourbillons, au large d’Irisia. Un gardien des mers dormirait dans leurs profondeurs ; des Corayon s’y accrochent aux rochers.', NULL, 'sea', 3000, true, '[{"type":"water","count":2}]'::jsonb, '["water","psychic"]'::jsonb, '[240,480]'::jsonb, '[{"speciesId":72,"weight":18,"minLevel":38,"maxLevel":44},{"speciesId":73,"weight":8,"minLevel":40,"maxLevel":46},{"speciesId":98,"weight":10,"minLevel":38,"maxLevel":44},{"speciesId":99,"weight":5,"minLevel":40,"maxLevel":46},{"speciesId":116,"weight":10,"minLevel":38,"maxLevel":44},{"speciesId":117,"weight":5,"minLevel":40,"maxLevel":46},{"speciesId":86,"weight":10,"minLevel":38,"maxLevel":44},{"speciesId":87,"weight":4,"minLevel":40,"maxLevel":46},{"speciesId":129,"weight":8,"minLevel":35,"maxLevel":45},{"speciesId":171,"weight":6,"minLevel":40,"maxLevel":46},{"speciesId":222,"weight":4,"minLevel":38,"maxLevel":44}]'::jsonb, 'butin-mer', '{"type":"questStepsDone","questId":"lugia","count":1}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
INSERT INTO "zones" ("content_version_id", "id", "region_id", "order", "name", "description", "image", "habitat", "min_power", "enabled", "required_types", "affinity_types", "durations_minutes", "encounters", "loot_table_id", "unlock")
SELECT v."id", 'tour-carillon', 'johto', 27, 'Tour Carillon', 'La tour à neuf étages de Rosalia. Ses cloches sonnent pour accueillir l’oiseau arc-en-ciel.', NULL, 'urban', 4000, true, '[]'::jsonb, '["fire","psychic","ghost"]'::jsonb, '[240,480]'::jsonb, '[{"speciesId":198,"weight":12,"minLevel":45,"maxLevel":50},{"speciesId":228,"weight":10,"minLevel":45,"maxLevel":50},{"speciesId":229,"weight":6,"minLevel":48,"maxLevel":52},{"speciesId":218,"weight":10,"minLevel":45,"maxLevel":50},{"speciesId":219,"weight":6,"minLevel":48,"maxLevel":52},{"speciesId":177,"weight":10,"minLevel":45,"maxLevel":50},{"speciesId":178,"weight":6,"minLevel":48,"maxLevel":52},{"speciesId":92,"weight":12,"minLevel":45,"maxLevel":50},{"speciesId":93,"weight":8,"minLevel":48,"maxLevel":52},{"speciesId":20,"weight":10,"minLevel":45,"maxLevel":50}]'::jsonb, 'butin-elite', '{"type":"questStepsDone","questId":"ho-oh","count":2}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
INSERT INTO "zones" ("content_version_id", "id", "region_id", "order", "name", "description", "image", "habitat", "min_power", "enabled", "required_types", "affinity_types", "durations_minutes", "encounters", "loot_table_id", "unlock")
SELECT v."id", 'autel-bois-aux-chenes', 'johto', 28, 'Autel du Bois aux Chênes', 'Le petit autel de bois, au cœur de la forêt. On raconte qu’un voyageur du temps y apparaît.', NULL, 'forest', 3600, true, '[]'::jsonb, '["grass","bug","psychic"]'::jsonb, '[240,480]'::jsonb, '[{"speciesId":204,"weight":14,"minLevel":40,"maxLevel":46},{"speciesId":205,"weight":6,"minLevel":42,"maxLevel":46},{"speciesId":191,"weight":12,"minLevel":40,"maxLevel":46},{"speciesId":192,"weight":6,"minLevel":42,"maxLevel":46},{"speciesId":188,"weight":10,"minLevel":40,"maxLevel":46},{"speciesId":189,"weight":6,"minLevel":42,"maxLevel":46},{"speciesId":166,"weight":8,"minLevel":40,"maxLevel":46},{"speciesId":168,"weight":8,"minLevel":40,"maxLevel":46},{"speciesId":47,"weight":8,"minLevel":40,"maxLevel":46},{"speciesId":45,"weight":6,"minLevel":42,"maxLevel":46}]'::jsonb, 'butin-foret', '{"type":"questStepsDone","questId":"celebi","count":2}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
UPDATE "trainers" SET "team" = '[{"speciesId":161,"level":4,"iv":null,"nature":null},{"speciesId":19,"level":4,"iv":null,"nature":null}]'::jsonb, "money" = 80
WHERE "id" = 'gamin-joey' AND "id" IS NOT DISTINCT FROM 'gamin-joey' AND "region_id" IS NOT DISTINCT FROM 'johto' AND "zone_id" IS NOT DISTINCT FROM 'route-29' AND "order" IS NOT DISTINCT FROM 0 AND "name" IS NOT DISTINCT FROM 'Joey' AND "trainer_class" IS NOT DISTINCT FROM 'Gamin' AND "sprite" IS NOT DISTINCT FROM '/api/sprites/trainers/youngster-gen4.png' AND "team" IS NOT DISTINCT FROM '[{"speciesId":161,"level":6,"iv":null,"nature":null},{"speciesId":19,"level":6,"iv":null,"nature":null}]'::jsonb AND "duration_minutes" IS NOT DISTINCT FROM 10 AND "rules" IS NOT DISTINCT FROM '{"teamSize":null,"maxLevel":null,"requiredTypes":[],"forbiddenTypes":[],"minPower":0}'::jsonb AND "money" IS NOT DISTINCT FROM 150 AND "loot_table_id" IS NOT DISTINCT FROM 'butin-route' AND "loot_rolls" IS NOT DISTINCT FROM 1 AND "badge" IS NOT DISTINCT FROM NULL AND "repeatable" IS NOT DISTINCT FROM true AND "cooldown_minutes" IS NOT DISTINCT FROM NULL AND "ko_minutes" IS NOT DISTINCT FROM NULL AND "enabled" IS NOT DISTINCT FROM true AND "unlock" IS NOT DISTINCT FROM '{"type":"always"}'::jsonb;--> statement-breakpoint
INSERT INTO "trainers" ("content_version_id", "id", "region_id", "zone_id", "order", "name", "trainer_class", "sprite", "team", "duration_minutes", "rules", "money", "loot_table_id", "loot_rolls", "badge", "repeatable", "cooldown_minutes", "ko_minutes", "enabled", "unlock")
SELECT v."id", 'scout-willy', 'johto', 'routes-30-31', 1, 'Willy', 'Scout', '/api/sprites/trainers/bugcatcher-gen3.png', '[{"speciesId":165,"level":5,"iv":null,"nature":null},{"speciesId":167,"level":5,"iv":null,"nature":null},{"speciesId":13,"level":6,"iv":null,"nature":null}]'::jsonb, 15, '{"teamSize":null,"maxLevel":null,"requiredTypes":[],"forbiddenTypes":[],"minPower":0}'::jsonb, 150, 'butin-foret', 1, NULL, true, NULL, NULL, true, '{"type":"regionDexPercent","regionId":"johto","percent":3}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
INSERT INTO "trainers" ("content_version_id", "id", "region_id", "zone_id", "order", "name", "trainer_class", "sprite", "team", "duration_minutes", "rules", "money", "loot_table_id", "loot_rolls", "badge", "repeatable", "cooldown_minutes", "ko_minutes", "enabled", "unlock")
SELECT v."id", 'sage-li', 'johto', 'tour-chetiflor', 2, 'Li', 'Sage', '/api/sprites/trainers/sage.png', '[{"speciesId":69,"level":7,"iv":null,"nature":null},{"speciesId":69,"level":7,"iv":null,"nature":null},{"speciesId":163,"level":10,"iv":null,"nature":null}]'::jsonb, 20, '{"teamSize":null,"maxLevel":null,"requiredTypes":[],"forbiddenTypes":[],"minPower":0}'::jsonb, 200, 'butin-grotte', 2, NULL, true, NULL, NULL, true, '{"type":"trainerDefeated","trainerId":"scout-willy"}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
UPDATE "trainers" SET "order" = 3, "team" = '[{"speciesId":16,"level":11,"iv":null,"nature":null},{"speciesId":17,"level":15,"iv":null,"nature":null}]'::jsonb, "rules" = '{"teamSize":2,"maxLevel":null,"requiredTypes":[],"forbiddenTypes":[],"minPower":160}'::jsonb, "money" = 1500, "unlock" = '{"type":"trainerDefeated","trainerId":"sage-li"}'::jsonb
WHERE "id" = 'albert' AND "id" IS NOT DISTINCT FROM 'albert' AND "region_id" IS NOT DISTINCT FROM 'johto' AND "zone_id" IS NOT DISTINCT FROM NULL AND "order" IS NOT DISTINCT FROM 1 AND "name" IS NOT DISTINCT FROM 'Albert' AND "trainer_class" IS NOT DISTINCT FROM 'Champion d’arène' AND "sprite" IS NOT DISTINCT FROM '/api/sprites/trainers/falkner.png' AND "team" IS NOT DISTINCT FROM '[{"speciesId":16,"level":13,"iv":null,"nature":null},{"speciesId":163,"level":14,"iv":null,"nature":null},{"speciesId":17,"level":16,"iv":null,"nature":null}]'::jsonb AND "duration_minutes" IS NOT DISTINCT FROM 60 AND "rules" IS NOT DISTINCT FROM '{"teamSize":null,"maxLevel":null,"requiredTypes":[],"forbiddenTypes":[],"minPower":0}'::jsonb AND "money" IS NOT DISTINCT FROM 1800 AND "loot_table_id" IS NOT DISTINCT FROM 'butin-route' AND "loot_rolls" IS NOT DISTINCT FROM 3 AND "badge" IS NOT DISTINCT FROM '{"name":"Badge Zéphyr","image":null}'::jsonb AND "repeatable" IS NOT DISTINCT FROM false AND "cooldown_minutes" IS NOT DISTINCT FROM NULL AND "ko_minutes" IS NOT DISTINCT FROM NULL AND "enabled" IS NOT DISTINCT FROM true AND "unlock" IS NOT DISTINCT FROM '{"type":"trainerDefeated","trainerId":"gamin-joey"}'::jsonb;--> statement-breakpoint
INSERT INTO "trainers" ("content_version_id", "id", "region_id", "zone_id", "order", "name", "trainer_class", "sprite", "team", "duration_minutes", "rules", "money", "loot_table_id", "loot_rolls", "badge", "repeatable", "cooldown_minutes", "ko_minutes", "enabled", "unlock")
SELECT v."id", 'pecheur-raoul', 'johto', 'route-32', 4, 'Raoul', 'Pêcheur', '/api/sprites/trainers/fisherman.png', '[{"speciesId":129,"level":10,"iv":null,"nature":null},{"speciesId":211,"level":12,"iv":null,"nature":null},{"speciesId":72,"level":11,"iv":null,"nature":null}]'::jsonb, 30, '{"teamSize":null,"maxLevel":null,"requiredTypes":[],"forbiddenTypes":[],"minPower":0}'::jsonb, 300, 'butin-mer', 2, NULL, true, NULL, NULL, true, '{"type":"badgeCount","count":1,"regionId":"johto"}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
INSERT INTO "trainers" ("content_version_id", "id", "region_id", "zone_id", "order", "name", "trainer_class", "sprite", "team", "duration_minutes", "rules", "money", "loot_table_id", "loot_rolls", "badge", "repeatable", "cooldown_minutes", "ko_minutes", "enabled", "unlock")
SELECT v."id", 'montagnard-anthony', 'johto', 'caves-jumelles', 5, 'Anthony', 'Montagnard', '/api/sprites/trainers/hiker-gen4.png', '[{"speciesId":74,"level":12,"iv":null,"nature":null},{"speciesId":41,"level":12,"iv":null,"nature":null},{"speciesId":95,"level":13,"iv":null,"nature":null}]'::jsonb, 30, '{"teamSize":null,"maxLevel":null,"requiredTypes":[],"forbiddenTypes":[],"minPower":0}'::jsonb, 360, 'butin-grotte', 2, NULL, true, NULL, NULL, true, '{"type":"trainerDefeated","trainerId":"pecheur-raoul"}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
INSERT INTO "trainers" ("content_version_id", "id", "region_id", "zone_id", "order", "name", "trainer_class", "sprite", "team", "duration_minutes", "rules", "money", "loot_table_id", "loot_rolls", "badge", "repeatable", "cooldown_minutes", "ko_minutes", "enabled", "unlock")
SELECT v."id", 'sbire-puits', 'johto', 'puits-ramoloss', 6, 'Sbire', 'Team Rocket', '/api/sprites/trainers/rocketgrunt.png', '[{"speciesId":19,"level":13,"iv":null,"nature":null},{"speciesId":23,"level":14,"iv":null,"nature":null},{"speciesId":41,"level":15,"iv":null,"nature":null}]'::jsonb, 30, '{"teamSize":null,"maxLevel":null,"requiredTypes":[],"forbiddenTypes":[],"minPower":0}'::jsonb, 450, 'butin-grotte', 2, NULL, true, NULL, NULL, true, '{"type":"trainerDefeated","trainerId":"montagnard-anthony"}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
INSERT INTO "trainers" ("content_version_id", "id", "region_id", "zone_id", "order", "name", "trainer_class", "sprite", "team", "duration_minutes", "rules", "money", "loot_table_id", "loot_rolls", "badge", "repeatable", "cooldown_minutes", "ko_minutes", "enabled", "unlock")
SELECT v."id", 'hector', 'johto', NULL, 7, 'Hector', 'Champion d’arène', '/api/sprites/trainers/bugsy.png', '[{"speciesId":11,"level":16,"iv":null,"nature":null},{"speciesId":14,"level":16,"iv":null,"nature":null},{"speciesId":123,"level":18,"iv":null,"nature":null}]'::jsonb, 60, '{"teamSize":3,"maxLevel":null,"requiredTypes":[],"forbiddenTypes":[],"minPower":290}'::jsonb, 1800, 'butin-foret', 3, '{"name":"Badge Essaim","image":null}'::jsonb, false, NULL, 120, true, '{"type":"trainerDefeated","trainerId":"sbire-puits"}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
INSERT INTO "trainers" ("content_version_id", "id", "region_id", "zone_id", "order", "name", "trainer_class", "sprite", "team", "duration_minutes", "rules", "money", "loot_table_id", "loot_rolls", "badge", "repeatable", "cooldown_minutes", "ko_minutes", "enabled", "unlock")
SELECT v."id", 'scout-hugo', 'johto', 'bois-aux-chenes', 8, 'Hugo', 'Scout', '/api/sprites/trainers/bugcatcher-gen3.png', '[{"speciesId":204,"level":16,"iv":null,"nature":null},{"speciesId":166,"level":17,"iv":null,"nature":null},{"speciesId":168,"level":17,"iv":null,"nature":null}]'::jsonb, 45, '{"teamSize":null,"maxLevel":null,"requiredTypes":[],"forbiddenTypes":[],"minPower":0}'::jsonb, 500, 'butin-foret', 2, NULL, true, NULL, NULL, true, '{"type":"badgeCount","count":2,"regionId":"johto"}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
INSERT INTO "trainers" ("content_version_id", "id", "region_id", "zone_id", "order", "name", "trainer_class", "sprite", "team", "duration_minutes", "rules", "money", "loot_table_id", "loot_rolls", "badge", "repeatable", "cooldown_minutes", "ko_minutes", "enabled", "unlock")
SELECT v."id", 'pique-niqueuse-gina', 'johto', 'routes-34-35', 9, 'Gina', 'Pique-niqueuse', '/api/sprites/trainers/picnicker.png', '[{"speciesId":209,"level":17,"iv":null,"nature":null},{"speciesId":191,"level":17,"iv":null,"nature":null},{"speciesId":39,"level":18,"iv":null,"nature":null}]'::jsonb, 45, '{"teamSize":null,"maxLevel":null,"requiredTypes":[],"forbiddenTypes":[],"minPower":0}'::jsonb, 550, 'butin-route', 2, NULL, true, NULL, NULL, true, '{"type":"trainerDefeated","trainerId":"scout-hugo"}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
INSERT INTO "trainers" ("content_version_id", "id", "region_id", "zone_id", "order", "name", "trainer_class", "sprite", "team", "duration_minutes", "rules", "money", "loot_table_id", "loot_rolls", "badge", "repeatable", "cooldown_minutes", "ko_minutes", "enabled", "unlock")
SELECT v."id", 'blanche', 'johto', NULL, 10, 'Blanche', 'Championne d’arène', '/api/sprites/trainers/whitney.png', '[{"speciesId":39,"level":20,"iv":null,"nature":null},{"speciesId":35,"level":21,"iv":null,"nature":null},{"speciesId":241,"level":24,"iv":null,"nature":null}]'::jsonb, 60, '{"teamSize":3,"maxLevel":null,"requiredTypes":[],"forbiddenTypes":[],"minPower":400}'::jsonb, 2400, 'butin-grotte', 3, '{"name":"Badge Plaine","image":null}'::jsonb, false, NULL, 120, true, '{"type":"trainerDefeated","trainerId":"pique-niqueuse-gina"}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
INSERT INTO "trainers" ("content_version_id", "id", "region_id", "zone_id", "order", "name", "trainer_class", "sprite", "team", "duration_minutes", "rules", "money", "loot_table_id", "loot_rolls", "badge", "repeatable", "cooldown_minutes", "ko_minutes", "enabled", "unlock")
SELECT v."id", 'mediume-edith', 'johto', 'tour-cendree', 11, 'Édith', 'Médium', '/api/sprites/trainers/medium.png', '[{"speciesId":92,"level":20,"iv":null,"nature":null},{"speciesId":92,"level":20,"iv":null,"nature":null},{"speciesId":93,"level":22,"iv":null,"nature":null},{"speciesId":228,"level":22,"iv":null,"nature":null}]'::jsonb, 60, '{"teamSize":null,"maxLevel":null,"requiredTypes":[],"forbiddenTypes":[],"minPower":0}'::jsonb, 900, 'butin-grotte', 2, NULL, true, NULL, NULL, true, '{"type":"badgeCount","count":3,"regionId":"johto"}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
INSERT INTO "trainers" ("content_version_id", "id", "region_id", "zone_id", "order", "name", "trainer_class", "sprite", "team", "duration_minutes", "rules", "money", "loot_table_id", "loot_rolls", "badge", "repeatable", "cooldown_minutes", "ko_minutes", "enabled", "unlock")
SELECT v."id", 'mortimer', 'johto', NULL, 12, 'Mortimer', 'Champion d’arène', '/api/sprites/trainers/morty.png', '[{"speciesId":92,"level":23,"iv":null,"nature":null},{"speciesId":93,"level":23,"iv":null,"nature":null},{"speciesId":93,"level":25,"iv":null,"nature":null},{"speciesId":94,"level":27,"iv":null,"nature":null}]'::jsonb, 60, '{"teamSize":4,"maxLevel":null,"requiredTypes":[],"forbiddenTypes":[],"minPower":640}'::jsonb, 2700, 'butin-grotte', 3, '{"name":"Badge Brume","image":null}'::jsonb, false, NULL, 120, true, '{"type":"trainerDefeated","trainerId":"mediume-edith"}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
INSERT INTO "trainers" ("content_version_id", "id", "region_id", "zone_id", "order", "name", "trainer_class", "sprite", "team", "duration_minutes", "rules", "money", "loot_table_id", "loot_rolls", "badge", "repeatable", "cooldown_minutes", "ko_minutes", "enabled", "unlock")
SELECT v."id", 'nageuse-marina', 'johto', 'routes-40-41', 13, 'Marina', 'Nageuse', '/api/sprites/trainers/swimmerf-gen4.png', '[{"speciesId":170,"level":26,"iv":null,"nature":null},{"speciesId":72,"level":26,"iv":null,"nature":null},{"speciesId":116,"level":27,"iv":null,"nature":null},{"speciesId":226,"level":28,"iv":null,"nature":null}]'::jsonb, 60, '{"teamSize":null,"maxLevel":null,"requiredTypes":[],"forbiddenTypes":[],"minPower":0}'::jsonb, 1300, 'butin-mer', 2, NULL, true, NULL, NULL, true, '{"type":"badgeCount","count":4,"regionId":"johto"}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
INSERT INTO "trainers" ("content_version_id", "id", "region_id", "zone_id", "order", "name", "trainer_class", "sprite", "team", "duration_minutes", "rules", "money", "loot_table_id", "loot_rolls", "badge", "repeatable", "cooldown_minutes", "ko_minutes", "enabled", "unlock")
SELECT v."id", 'chuck', 'johto', NULL, 14, 'Chuck', 'Champion d’arène', '/api/sprites/trainers/chuck.png', '[{"speciesId":56,"level":30,"iv":null,"nature":null},{"speciesId":66,"level":30,"iv":null,"nature":null},{"speciesId":57,"level":32,"iv":null,"nature":null},{"speciesId":62,"level":34,"iv":null,"nature":null}]'::jsonb, 90, '{"teamSize":4,"maxLevel":null,"requiredTypes":[],"forbiddenTypes":[],"minPower":780}'::jsonb, 3400, 'butin-grotte', 3, '{"name":"Badge Choc","image":null}'::jsonb, false, NULL, 120, true, '{"type":"trainerDefeated","trainerId":"nageuse-marina"}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
INSERT INTO "trainers" ("content_version_id", "id", "region_id", "zone_id", "order", "name", "trainer_class", "sprite", "team", "duration_minutes", "rules", "money", "loot_table_id", "loot_rolls", "badge", "repeatable", "cooldown_minutes", "ko_minutes", "enabled", "unlock")
SELECT v."id", 'marin-gilles', 'johto', 'phare-oliville', 15, 'Gilles', 'Marin', '/api/sprites/trainers/sailor.png', '[{"speciesId":72,"level":30,"iv":null,"nature":null},{"speciesId":81,"level":30,"iv":null,"nature":null},{"speciesId":171,"level":31,"iv":null,"nature":null},{"speciesId":82,"level":32,"iv":null,"nature":null}]'::jsonb, 60, '{"teamSize":null,"maxLevel":null,"requiredTypes":[],"forbiddenTypes":[],"minPower":0}'::jsonb, 1600, 'butin-mer', 2, NULL, true, NULL, NULL, true, '{"type":"badgeCount","count":5,"regionId":"johto"}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
INSERT INTO "trainers" ("content_version_id", "id", "region_id", "zone_id", "order", "name", "trainer_class", "sprite", "team", "duration_minutes", "rules", "money", "loot_table_id", "loot_rolls", "badge", "repeatable", "cooldown_minutes", "ko_minutes", "enabled", "unlock")
SELECT v."id", 'jasmine', 'johto', NULL, 16, 'Jasmine', 'Championne d’arène', '/api/sprites/trainers/jasmine.png', '[{"speciesId":81,"level":34,"iv":18,"nature":null},{"speciesId":82,"level":35,"iv":18,"nature":null},{"speciesId":205,"level":35,"iv":18,"nature":null},{"speciesId":208,"level":39,"iv":18,"nature":null}]'::jsonb, 90, '{"teamSize":4,"maxLevel":null,"requiredTypes":[],"forbiddenTypes":[],"minPower":970}'::jsonb, 3900, 'butin-grotte', 3, '{"name":"Badge Minéral","image":null}'::jsonb, false, NULL, 120, true, '{"type":"trainerDefeated","trainerId":"marin-gilles"}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
INSERT INTO "trainers" ("content_version_id", "id", "region_id", "zone_id", "order", "name", "trainer_class", "sprite", "team", "duration_minutes", "rules", "money", "loot_table_id", "loot_rolls", "badge", "repeatable", "cooldown_minutes", "ko_minutes", "enabled", "unlock")
SELECT v."id", 'sbire-qg-rocket', 'johto', NULL, 17, 'Sbire', 'Team Rocket', '/api/sprites/trainers/rocketgrunt.png', '[{"speciesId":24,"level":33,"iv":null,"nature":null},{"speciesId":89,"level":33,"iv":null,"nature":null},{"speciesId":110,"level":34,"iv":null,"nature":null},{"speciesId":20,"level":34,"iv":null,"nature":null}]'::jsonb, 60, '{"teamSize":null,"maxLevel":null,"requiredTypes":[],"forbiddenTypes":[],"minPower":0}'::jsonb, 1800, 'butin-grotte', 2, NULL, true, NULL, NULL, true, '{"type":"badgeCount","count":6,"regionId":"johto"}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
INSERT INTO "trainers" ("content_version_id", "id", "region_id", "zone_id", "order", "name", "trainer_class", "sprite", "team", "duration_minutes", "rules", "money", "loot_table_id", "loot_rolls", "badge", "repeatable", "cooldown_minutes", "ko_minutes", "enabled", "unlock")
SELECT v."id", 'fredo', 'johto', NULL, 18, 'Frédo', 'Champion d’arène', '/api/sprites/trainers/pryce.png', '[{"speciesId":86,"level":36,"iv":20,"nature":null},{"speciesId":124,"level":37,"iv":20,"nature":null},{"speciesId":91,"level":37,"iv":20,"nature":null},{"speciesId":87,"level":38,"iv":20,"nature":null},{"speciesId":221,"level":40,"iv":20,"nature":null}]'::jsonb, 90, '{"teamSize":5,"maxLevel":null,"requiredTypes":[],"forbiddenTypes":[],"minPower":1290}'::jsonb, 4000, 'butin-grotte', 3, '{"name":"Badge Glacier","image":null}'::jsonb, false, NULL, 120, true, '{"type":"trainerDefeated","trainerId":"sbire-qg-rocket"}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
INSERT INTO "trainers" ("content_version_id", "id", "region_id", "zone_id", "order", "name", "trainer_class", "sprite", "team", "duration_minutes", "rules", "money", "loot_table_id", "loot_rolls", "badge", "repeatable", "cooldown_minutes", "ko_minutes", "enabled", "unlock")
SELECT v."id", 'skieuse-rosa', 'johto', 'route-de-glace', 19, 'Rosa', 'Skieuse', '/api/sprites/trainers/skier.png', '[{"speciesId":220,"level":35,"iv":null,"nature":null},{"speciesId":86,"level":35,"iv":null,"nature":null},{"speciesId":225,"level":36,"iv":null,"nature":null},{"speciesId":215,"level":37,"iv":null,"nature":null},{"speciesId":87,"level":37,"iv":null,"nature":null}]'::jsonb, 60, '{"teamSize":null,"maxLevel":null,"requiredTypes":[],"forbiddenTypes":[],"minPower":0}'::jsonb, 2200, 'butin-grotte', 2, NULL, true, NULL, NULL, true, '{"type":"badgeCount","count":7,"regionId":"johto"}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
INSERT INTO "trainers" ("content_version_id", "id", "region_id", "zone_id", "order", "name", "trainer_class", "sprite", "team", "duration_minutes", "rules", "money", "loot_table_id", "loot_rolls", "badge", "repeatable", "cooldown_minutes", "ko_minutes", "enabled", "unlock")
SELECT v."id", 'sandra', 'johto', NULL, 20, 'Sandra', 'Championne d’arène', '/api/sprites/trainers/clair.png', '[{"speciesId":148,"level":40,"iv":25,"nature":null},{"speciesId":148,"level":40,"iv":25,"nature":null},{"speciesId":148,"level":40,"iv":25,"nature":null},{"speciesId":130,"level":41,"iv":25,"nature":null},{"speciesId":230,"level":44,"iv":25,"nature":null}]'::jsonb, 120, '{"teamSize":5,"maxLevel":null,"requiredTypes":[],"forbiddenTypes":[],"minPower":1480}'::jsonb, 4400, 'butin-elite', 3, '{"name":"Badge Lever","image":null}'::jsonb, false, NULL, 180, true, '{"type":"trainerDefeated","trainerId":"skieuse-rosa"}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
INSERT INTO "trainers" ("content_version_id", "id", "region_id", "zone_id", "order", "name", "trainer_class", "sprite", "team", "duration_minutes", "rules", "money", "loot_table_id", "loot_rolls", "badge", "repeatable", "cooldown_minutes", "ko_minutes", "enabled", "unlock")
SELECT v."id", 'topdresseur-gaston', 'johto', 'routes-26-27', 21, 'Gaston', 'Topdresseur', '/api/sprites/trainers/acetrainer-gen4.png', '[{"speciesId":181,"level":44,"iv":20,"nature":null},{"speciesId":229,"level":44,"iv":20,"nature":null},{"speciesId":195,"level":43,"iv":20,"nature":null},{"speciesId":232,"level":44,"iv":20,"nature":null},{"speciesId":164,"level":43,"iv":20,"nature":null}]'::jsonb, 90, '{"teamSize":null,"maxLevel":null,"requiredTypes":[],"forbiddenTypes":[],"minPower":0}'::jsonb, 3500, 'butin-elite', 2, NULL, true, NULL, NULL, true, '{"type":"badgeCount","count":8,"regionId":"johto"}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
INSERT INTO "trainers" ("content_version_id", "id", "region_id", "zone_id", "order", "name", "trainer_class", "sprite", "team", "duration_minutes", "rules", "money", "loot_table_id", "loot_rolls", "badge", "repeatable", "cooldown_minutes", "ko_minutes", "enabled", "unlock")
SELECT v."id", 'clement', 'johto', NULL, 22, 'Clément', 'Conseil 4', '/api/sprites/trainers/will.png', '[{"speciesId":178,"level":50,"iv":25,"nature":null},{"speciesId":124,"level":51,"iv":25,"nature":null},{"speciesId":103,"level":51,"iv":25,"nature":null},{"speciesId":80,"level":51,"iv":25,"nature":null},{"speciesId":178,"level":53,"iv":25,"nature":null}]'::jsonb, 120, '{"teamSize":null,"maxLevel":null,"requiredTypes":[],"forbiddenTypes":[],"minPower":0}'::jsonb, 7000, 'butin-elite', 3, NULL, false, NULL, 240, true, '{"type":"allOf","conditions":[{"type":"badgeCount","count":8,"regionId":"johto"},{"type":"trainerDefeated","trainerId":"topdresseur-gaston"}]}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
INSERT INTO "trainers" ("content_version_id", "id", "region_id", "zone_id", "order", "name", "trainer_class", "sprite", "team", "duration_minutes", "rules", "money", "loot_table_id", "loot_rolls", "badge", "repeatable", "cooldown_minutes", "ko_minutes", "enabled", "unlock")
SELECT v."id", 'koga-conseil', 'johto', NULL, 23, 'Koga', 'Conseil 4', '/api/sprites/trainers/koga.png', '[{"speciesId":168,"level":51,"iv":25,"nature":null},{"speciesId":49,"level":52,"iv":25,"nature":null},{"speciesId":205,"level":54,"iv":25,"nature":null},{"speciesId":89,"level":53,"iv":25,"nature":null},{"speciesId":169,"level":55,"iv":25,"nature":null}]'::jsonb, 120, '{"teamSize":null,"maxLevel":null,"requiredTypes":[],"forbiddenTypes":[],"minPower":0}'::jsonb, 7000, 'butin-elite', 3, NULL, false, NULL, 240, true, '{"type":"trainerDefeated","trainerId":"clement"}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
INSERT INTO "trainers" ("content_version_id", "id", "region_id", "zone_id", "order", "name", "trainer_class", "sprite", "team", "duration_minutes", "rules", "money", "loot_table_id", "loot_rolls", "badge", "repeatable", "cooldown_minutes", "ko_minutes", "enabled", "unlock")
SELECT v."id", 'aldo-johto', 'johto', NULL, 24, 'Aldo', 'Conseil 4', '/api/sprites/trainers/bruno.png', '[{"speciesId":237,"level":53,"iv":25,"nature":null},{"speciesId":106,"level":53,"iv":25,"nature":null},{"speciesId":107,"level":53,"iv":25,"nature":null},{"speciesId":95,"level":54,"iv":25,"nature":null},{"speciesId":68,"level":57,"iv":25,"nature":null}]'::jsonb, 120, '{"teamSize":null,"maxLevel":null,"requiredTypes":[],"forbiddenTypes":[],"minPower":0}'::jsonb, 7000, 'butin-elite', 3, NULL, false, NULL, 240, true, '{"type":"trainerDefeated","trainerId":"koga-conseil"}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
INSERT INTO "trainers" ("content_version_id", "id", "region_id", "zone_id", "order", "name", "trainer_class", "sprite", "team", "duration_minutes", "rules", "money", "loot_table_id", "loot_rolls", "badge", "repeatable", "cooldown_minutes", "ko_minutes", "enabled", "unlock")
SELECT v."id", 'marion', 'johto', NULL, 25, 'Marion', 'Conseil 4', '/api/sprites/trainers/karen.png', '[{"speciesId":197,"level":54,"iv":25,"nature":null},{"speciesId":45,"level":54,"iv":25,"nature":null},{"speciesId":198,"level":56,"iv":25,"nature":null},{"speciesId":94,"level":57,"iv":25,"nature":null},{"speciesId":229,"level":59,"iv":25,"nature":null}]'::jsonb, 120, '{"teamSize":null,"maxLevel":null,"requiredTypes":[],"forbiddenTypes":[],"minPower":0}'::jsonb, 7000, 'butin-elite', 3, NULL, false, NULL, 240, true, '{"type":"trainerDefeated","trainerId":"aldo-johto"}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
INSERT INTO "trainers" ("content_version_id", "id", "region_id", "zone_id", "order", "name", "trainer_class", "sprite", "team", "duration_minutes", "rules", "money", "loot_table_id", "loot_rolls", "badge", "repeatable", "cooldown_minutes", "ko_minutes", "enabled", "unlock")
SELECT v."id", 'maitre-peter', 'johto', NULL, 26, 'Peter', 'Maître de la Ligue', '/api/sprites/trainers/lance.png', '[{"speciesId":130,"level":58,"iv":31,"nature":null},{"speciesId":149,"level":60,"iv":31,"nature":null},{"speciesId":149,"level":60,"iv":31,"nature":null},{"speciesId":142,"level":59,"iv":31,"nature":null},{"speciesId":6,"level":59,"iv":31,"nature":null},{"speciesId":149,"level":63,"iv":31,"nature":null}]'::jsonb, 180, '{"teamSize":null,"maxLevel":null,"requiredTypes":[],"forbiddenTypes":[],"minPower":0}'::jsonb, 18000, 'butin-elite', 5, NULL, false, NULL, 240, true, '{"type":"trainerDefeated","trainerId":"marion"}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
INSERT INTO "trainers" ("content_version_id", "id", "region_id", "zone_id", "order", "name", "trainer_class", "sprite", "team", "duration_minutes", "rules", "money", "loot_table_id", "loot_rolls", "badge", "repeatable", "cooldown_minutes", "ko_minutes", "enabled", "unlock")
SELECT v."id", 'red', 'johto', 'mont-argente', 27, 'Red', 'Dresseur légendaire', '/api/sprites/trainers/red.png', '[{"speciesId":25,"level":81,"iv":31,"nature":null},{"speciesId":196,"level":73,"iv":31,"nature":null},{"speciesId":143,"level":75,"iv":31,"nature":null},{"speciesId":3,"level":77,"iv":31,"nature":null},{"speciesId":6,"level":77,"iv":31,"nature":null},{"speciesId":9,"level":77,"iv":31,"nature":null}]'::jsonb, 240, '{"teamSize":null,"maxLevel":null,"requiredTypes":[],"forbiddenTypes":[],"minPower":0}'::jsonb, 30000, 'butin-elite', 6, NULL, false, NULL, 480, true, '{"type":"allOf","conditions":[{"type":"trainerDefeated","trainerId":"maitre-peter"},{"type":"trainerDefeated","trainerId":"maitre-blue"}]}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
INSERT INTO "quests" ("content_version_id", "id", "order", "name", "description", "image", "region_id", "enabled", "unlock", "steps", "rewards")
SELECT v."id", 'raikou', 0, 'La bête du tonnerre', 'Un grondement de tonnerre résonne sous la Tour Cendrée.', NULL, 'johto', true, '{"type":"badgeCount","count":4,"regionId":"johto"}'::jsonb, '[{"name":"Orage","description":"Capture 10 Pokémon Électrik.","condition":{"type":"catchPokemon","count":10,"pokemonType":"electric","speciesId":null}},{"name":"Les cendres","description":"Capture 5 Pokémon Feu.","condition":{"type":"catchPokemon","count":5,"pokemonType":"fire","speciesId":null}},{"name":"Le sous-sol de la tour","description":"Réussis une expédition à la Tour Cendrée avec 2 Pokémon Électrik de PE 350 ou plus.","condition":{"type":"expedition","zoneId":"tour-cendree","count":1,"memberType":"electric","memberCount":2,"minMemberPower":350}}]'::jsonb, '{"currency":12000,"items":[{"itemId":"bottle-cap","quantity":1}],"expeditionSlots":0,"battleSlots":0,"daycareSlots":0,"bonuses":[],"pokemon":[{"speciesId":243,"level":50,"perfectIvs":3}]}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
INSERT INTO "quests" ("content_version_id", "id", "order", "name", "description", "image", "region_id", "enabled", "unlock", "steps", "rewards")
SELECT v."id", 'entei', 1, 'La bête du volcan', 'Une bête de feu aurait fui la Tour Cendrée en faisant trembler la terre.', NULL, 'johto', true, '{"type":"badgeCount","count":5,"regionId":"johto"}'::jsonb, '[{"name":"Braises","description":"Capture 10 Pokémon Feu.","condition":{"type":"catchPokemon","count":10,"pokemonType":"fire","speciesId":null}},{"name":"Sur ses traces","description":"Capture 40 % du Pokédex de Johto.","condition":{"type":"regionDexPercent","regionId":"johto","percent":40}},{"name":"Le brasier","description":"Réussis une expédition à la Tour Cendrée avec 2 Pokémon Feu de PE 450 ou plus.","condition":{"type":"expedition","zoneId":"tour-cendree","count":1,"memberType":"fire","memberCount":2,"minMemberPower":450}}]'::jsonb, '{"currency":12000,"items":[{"itemId":"bottle-cap","quantity":1}],"expeditionSlots":0,"battleSlots":0,"daycareSlots":0,"bonuses":[],"pokemon":[{"speciesId":244,"level":50,"perfectIvs":3}]}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
INSERT INTO "quests" ("content_version_id", "id", "order", "name", "description", "image", "region_id", "enabled", "unlock", "steps", "rewards")
SELECT v."id", 'suicune', 2, 'La bête des aurores', 'Une bête aux reflets de cristal court sur l’eau du Lac Colère.', NULL, 'johto', true, '{"type":"badgeCount","count":6,"regionId":"johto"}'::jsonb, '[{"name":"Eaux pures","description":"Capture 15 Pokémon Eau.","condition":{"type":"catchPokemon","count":15,"pokemonType":"water","speciesId":null}},{"name":"Le vent du nord","description":"Bats Frédo, le Champion d’Acajou.","condition":{"type":"trainerDefeated","trainerId":"fredo"}},{"name":"Sur le lac","description":"Réussis une expédition au Lac Colère avec 2 Pokémon Eau de PE 500 ou plus.","condition":{"type":"expedition","zoneId":"lac-colere","count":1,"memberType":"water","memberCount":2,"minMemberPower":500}}]'::jsonb, '{"currency":12000,"items":[{"itemId":"bottle-cap","quantity":1}],"expeditionSlots":0,"battleSlots":0,"daycareSlots":0,"bonuses":[],"pokemon":[{"speciesId":245,"level":50,"perfectIvs":3}]}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
INSERT INTO "quests" ("content_version_id", "id", "order", "name", "description", "image", "region_id", "enabled", "unlock", "steps", "rewards")
SELECT v."id", 'lugia', 3, 'Le gardien des mers', 'Les tourbillons des Tourb’Îles cacheraient un Pokémon aux ailes d’argent.', NULL, 'johto', true, '{"type":"badgeCount","count":7,"regionId":"johto"}'::jsonb, '[{"name":"Plongée","description":"Capture 20 Pokémon Eau pour franchir les tourbillons.","condition":{"type":"catchPokemon","count":20,"pokemonType":"water","speciesId":null}},{"name":"Le chant des kimonos","description":"Bats Sandra, la Championne d’Ebenelle.","condition":{"type":"trainerDefeated","trainerId":"sandra"}},{"name":"Esprits","description":"Capture 10 Pokémon Psy.","condition":{"type":"catchPokemon","count":10,"pokemonType":"psychic","speciesId":null}},{"name":"Les profondeurs","description":"Réussis une expédition aux Tourb’Îles avec 2 Pokémon Psy de PE 600 ou plus.","condition":{"type":"expedition","zoneId":"tourb-iles","count":1,"memberType":"psychic","memberCount":2,"minMemberPower":600}}]'::jsonb, '{"currency":40000,"items":[{"itemId":"gold-bottle-cap","quantity":1}],"expeditionSlots":0,"battleSlots":0,"daycareSlots":0,"bonuses":[],"pokemon":[{"speciesId":249,"level":70,"perfectIvs":3}]}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
INSERT INTO "quests" ("content_version_id", "id", "order", "name", "description", "image", "region_id", "enabled", "unlock", "steps", "rewards")
SELECT v."id", 'ho-oh', 4, 'L’oiseau arc-en-ciel', 'Les cloches de la Tour Carillon attendent un dresseur digne de l’oiseau sacré.', NULL, 'johto', true, '{"type":"badgeCount","count":8,"regionId":"johto"}'::jsonb, '[{"name":"Les trois bêtes","description":"Termine les quêtes de Raikou, d’Entei et de Suicune.","condition":{"type":"allOf","conditions":[{"type":"questCompleted","questId":"raikou"},{"type":"questCompleted","questId":"entei"},{"type":"questCompleted","questId":"suicune"}]}},{"name":"Maître de Johto","description":"Bats Peter, le Maître de la Ligue.","condition":{"type":"trainerDefeated","trainerId":"maitre-peter"}},{"name":"Chercheur","description":"Capture 80 % du Pokédex de Johto.","condition":{"type":"regionDexPercent","regionId":"johto","percent":80}},{"name":"Le sommet de la tour","description":"Réussis une expédition à la Tour Carillon avec 3 Pokémon Feu de PE 750 ou plus.","condition":{"type":"expedition","zoneId":"tour-carillon","count":1,"memberType":"fire","memberCount":3,"minMemberPower":750}}]'::jsonb, '{"currency":50000,"items":[{"itemId":"gold-bottle-cap","quantity":1}],"expeditionSlots":0,"battleSlots":0,"daycareSlots":0,"bonuses":[],"pokemon":[{"speciesId":250,"level":70,"perfectIvs":3}]}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
INSERT INTO "quests" ("content_version_id", "id", "order", "name", "description", "image", "region_id", "enabled", "unlock", "steps", "rewards")
SELECT v."id", 'celebi', 5, 'Le voyageur du temps', 'Lugia et Ho-Oh apaisés, l’autel du Bois aux Chênes se met à briller.', NULL, 'johto', true, '{"type":"allOf","conditions":[{"type":"questCompleted","questId":"lugia"},{"type":"questCompleted","questId":"ho-oh"}]}'::jsonb, '[{"name":"Générations","description":"Fais éclore 40 œufs.","condition":{"type":"eggsHatched","count":40}},{"name":"Presque complet","description":"Capture 95 % du Pokédex de Johto.","condition":{"type":"regionDexPercent","regionId":"johto","percent":95}},{"name":"Le souffle des bois","description":"Capture 30 Pokémon Plante.","condition":{"type":"catchPokemon","count":30,"pokemonType":"grass","speciesId":null}},{"name":"L’autel","description":"Réussis 3 expéditions à l’Autel du Bois aux Chênes.","condition":{"type":"expedition","zoneId":"autel-bois-aux-chenes","count":3,"memberType":null,"memberCount":0,"minMemberPower":0}}]'::jsonb, '{"currency":0,"items":[{"itemId":"ability-patch","quantity":1}],"expeditionSlots":0,"battleSlots":0,"daycareSlots":0,"bonuses":[],"pokemon":[{"speciesId":251,"level":30,"perfectIvs":3}]}'::jsonb FROM "content_versions" v
WHERE EXISTS (SELECT 1 FROM "regions" r WHERE r."content_version_id" = v."id" AND r."id" = 'johto')
ON CONFLICT ("content_version_id", "id") DO NOTHING;--> statement-breakpoint
UPDATE "regions" SET "species_ids" = '[152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251]'::jsonb WHERE "id" = 'johto' AND "species_ids" = '[152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,246,247,248]'::jsonb;--> statement-breakpoint
UPDATE "regions" SET "starter_species_ids" = '[152,155,158]'::jsonb WHERE "id" = 'johto' AND "starter_species_ids" = '[]'::jsonb;--> statement-breakpoint
UPDATE "regions" SET "enabled" = true WHERE "id" = 'johto' AND "enabled" = false;--> statement-breakpoint
UPDATE "zones" SET "unlock" = regexp_replace("unlock"::text, '"type": "badgeCount", "count": ([0-9]+)}', '"type": "badgeCount", "count": \1, "regionId": "kanto"}', 'g')::jsonb WHERE "region_id" = 'kanto' AND "unlock"::text ~ '"type": "badgeCount", "count": [0-9]+}';--> statement-breakpoint
UPDATE "trainers" SET "unlock" = regexp_replace("unlock"::text, '"type": "badgeCount", "count": ([0-9]+)}', '"type": "badgeCount", "count": \1, "regionId": "kanto"}', 'g')::jsonb WHERE "region_id" = 'kanto' AND "unlock"::text ~ '"type": "badgeCount", "count": [0-9]+}';--> statement-breakpoint
UPDATE "quests" SET "unlock" = regexp_replace("unlock"::text, '"type": "badgeCount", "count": ([0-9]+)}', '"type": "badgeCount", "count": \1, "regionId": "kanto"}', 'g')::jsonb WHERE "region_id" = 'kanto' AND "unlock"::text ~ '"type": "badgeCount", "count": [0-9]+}';--> statement-breakpoint
UPDATE "quests" SET "steps" = regexp_replace("steps"::text, '"type": "badgeCount", "count": ([0-9]+)}', '"type": "badgeCount", "count": \1, "regionId": "kanto"}', 'g')::jsonb WHERE "region_id" = 'kanto' AND "steps"::text ~ '"type": "badgeCount", "count": [0-9]+}';
